1. Variables:

Variables are labels/names used to store the data values in memory.
   Variable name can contain only letters, numbers and _underscore, and cannot start with a number.
   These are case sensitive, like... employee_name and Employee_name

In [3]:
employee_id =1234 # employee_id is variable
employee_name = "MK" # employee_name is variable
Employee_name = "madkos"
employee_desig = "AI/ML" # employee_desig is variable
print(f"EMPLOYEE_NAME: {employee_name}") # we can observe case sensitive here
print(f"employee_name: {Employee_name}") 
print(f"Employee_DESIGNATION is: {employee_desig}")


EMPLOYEE_NAME: MK
employee_name: madkos
Employee_DESIGNATION is: AI/ML


2. DataTypes:

Data Types in python are nothing but describes the type of data inside the variable, python identifies the datatype automatically
   type() is the keyword to know the type of data.
   DataTypes are classified into different types.
   1. integer - defined as int(), whole numbers without decimal.
   2. string - defined as str(), text inside quotes.
   3. float - defined as float(), numbers with decimal point.
   4. boolean - defined as bool: TRUE or FALSE.
   5. list - defined with [], it can be changable, and allows duplicates, used to store multiple values with same datatype.
   6. tuple - defined with (), it cannot be changable, fixed, used to store the data in differnt datatypes.
   7. set - defined with {}, only unique values, no order,
   8. dictionary - defined with {}: 

In [2]:

print("--- PYTHON DATA TYPES WITH DEFINITIONS ---\n")

# 1. int - Definition: Stores whole numbers without decimal point. Used for counting.
leaves_taken = 2
print(f"Leaves_taken= {leaves_taken} | Type: {type(leaves_taken)}")

# 2. float - Definition: Stores decimal numbers. Used for precise values like salary, price.
net_salary_credited = 41250.75
print(f" NET_Salary_credited= {net_salary_credited} | Type: {type(net_salary_credited)}")

# 3. complex - Definition: Stores complex numbers in form a+bj. Used in scientific calculations.
location_coordinate = 16 + 80j
print(f"Location_coordinate= {location_coordinate}| Type: {type(location_coordinate)}")

# 4. str - Definition: Stores sequence of characters/text inside single or double quotes.
work_status = "Work From Office"
print(f"Work_status= {work_status} | Type: {type(work_status)}")

# 5. bool - Definition: Stores only True or False. Used for decision making / conditions.
is_punched_in = True
print(f"Punched_in= {is_punched_in} | Type: {type(is_punched_in)}")

# 6. list - Definition: Ordered, changeable collection that allows duplicates. Written in [].
today_tasks = ["Payroll Report", "Jupyter Practice", "Team Meeting"]
print(f"Today_tasks are= {today_tasks} | Type: {type(today_tasks)}")

# 7. tuple - Definition: Ordered, unchangeable collection that allows duplicates. Written in ().
id_card_info = ("25-04-2000", "O+", "Vijayawada")
print(f"Id_card_info= {id_card_info} | Type: {type(id_card_info)}")

# 8. set - Definition: Unordered, unindexed collection with no duplicate values. Written in {{}}.
departments_submitted = {"HR", "AI/ML", "HR", "Finance"}
print(f"Departments_submitted= {departments_submitted} | Type: {type(departments_submitted)}")

# 9. frozenset - Definition: Same as set but immutable (cannot be changed after creation).
frozen_departments = frozenset({"HR", "Finance"})
print(f"Frozen_departments are= {frozen_departments} | Type: {type(frozen_departments)}")

# 10. dict - Definition: Stores data in Key:Value pairs. Ordered, changeable, no duplicate keys.
payroll_record = {"emp_id": 1234, "name": "MK", "designation": "AI Intern"}
print(f"Payroll_record= {payroll_record} | Type: {type(payroll_record)}")

# 11. range - Definition: Represents a sequence of numbers. Used in loops.
emp_ids_range = range(101, 105)
print(f"Emp_ids_Range= {list(emp_ids_range)} | Type: {type(emp_ids_range)}")

# 12. NoneType - Definition: Represents absence of value / nothing. Only one value is None.
resignation_date = None
print(f"Resignation_date is= {resignation_date} | Type: {type(resignation_date)}")

--- PYTHON DATA TYPES WITH DEFINITIONS ---

Leaves_taken= 2 | Type: <class 'int'>
 NET_Salary_credited= 41250.75 | Type: <class 'float'>
Location_coordinate= (16+80j)| Type: <class 'complex'>
Work_status= Work From Office | Type: <class 'str'>
Punched_in= True | Type: <class 'bool'>
Today_tasks are= ['Payroll Report', 'Jupyter Practice', 'Team Meeting'] | Type: <class 'list'>
Id_card_info= ('25-04-2000', 'O+', 'Vijayawada') | Type: <class 'tuple'>
Departments_submitted= {'AI/ML', 'Finance', 'HR'} | Type: <class 'set'>
Frozen_departments are= frozenset({'Finance', 'HR'}) | Type: <class 'frozenset'>
Payroll_record= {'emp_id': 1234, 'name': 'MK', 'designation': 'AI Intern'} | Type: <class 'dict'>
Emp_ids_Range= [101, 102, 103, 104] | Type: <class 'range'>
Resignation_date is= None | Type: <class 'NoneType'>


3. TYPE CASTING
   Converting the data from one data type to another data type.
   It is 2 types. 1. Implicit Casting: Python does it automatically.
                  2. Explicit Casting: We do manually using int(),str(),float(),..etc

In [4]:
# Real-time: Work hours is 7.75 hours, but need to show only full hours
work_hours = 8.75
full_hours_only = int(work_hours) # removes decimal
print(full_hours_only) #8
print(type(full_hours_only)) # class <int>

8
<class 'int'>


OPERATORS:

Operators are special symbols in Python that tell the computer to do some operation on values.
Think of it like this: If variables are like boxes to store data,
Python has 7 main types of operators:
Arithmetic: For maths (+, -, _, /, %)
Comparison: For comparing (==, !=, >, <)
Logical: For combining conditions (and, or, not)
Assignment: For assigning values (=, +=, -=)
Membership: For checking if value is inside a collection (in, not in)
Identity: For checking if two variables are same memory location (is, is not)
Bitwise: For working at binary level (&, |)

In [5]:
# OPERATORS- Hostel Mess Bill System
# Initial Data
per_day_cost = 100 # int
days_eaten = 27 # int
is_fee_paid = True # bool
defaulter_list = ["Amit", "Suresh", "Ravi"] # list
student_name = "Madhuri"

print("--- 1. ARITHMETIC OPERATOR ---")
# Calculating total bill
total_bill = per_day_cost * days_eaten # * is arithmetic
remaining_days = 30 % days_eaten # % gives remainder
print(f"Total Bill: {per_day_cost} * {days_eaten} = {total_bill}")
print(f"Remaining days in month: {remaining_days}")

print("\n--- 2. ASSIGNMENT OPERATOR ---")
# Adding extra maintenance charge
total_bill += 200 # Same as total_bill = total_bill + 200
print(f"After adding maintenance (total_bill += 200): {total_bill}")

print("\n--- 3. COMPARISON OPERATOR ---")
# Checking for bonus eligibility
is_eligible_for_sweet = days_eaten > 25 # > is comparison
print(f"Is {days_eaten} > 25? {is_eligible_for_sweet}")

print("\n--- 4. LOGICAL OPERATOR ---")
# Bonus only if days > 25 AND fee is paid
if days_eaten > 25 and is_fee_paid == True: # and is logical
    print("Eligible for Free Sweet - Both conditions True")
else:
    print("Not Eligible for Sweet")

print("\n--- 5. MEMBERSHIP OPERATOR ---")
# Checking if student is defaulter
is_defaulter = student_name in defaulter_list # in is membership
print(f"Is {student_name} in defaulter_list? {is_defaulter}")

print("\n--- 6. IDENTITY OPERATOR ---")
# Checking if two variables point to same object
bill_a = 3500
bill_b = 3500
bill_c = bill_a
print(f"bill_a is bill_b? {bill_a is bill_b}") # False for small demo, but checks memory
print(f"bill_a is bill_c? {bill_a is bill_c}") # True, because bill_c = bill_a

--- 1. ARITHMETIC OPERATOR ---
Total Bill: 100 * 27 = 2700
Remaining days in month: 3

--- 2. ASSIGNMENT OPERATOR ---
After adding maintenance (total_bill += 200): 2900

--- 3. COMPARISON OPERATOR ---
Is 27 > 25? True

--- 4. LOGICAL OPERATOR ---
Eligible for Free Sweet - Both conditions True

--- 5. MEMBERSHIP OPERATOR ---
Is Madhuri in defaulter_list? False

--- 6. IDENTITY OPERATOR ---
bill_a is bill_b? False
bill_a is bill_c? True


per_day_cost * days_eaten -> Arithmetic Operator.
total_bill += 200 -> Assignment Operator.
days_eaten > 25 -> Comparison Operator.
days_eaten > 25 and is_fee_paid == True -> Logical Operator.
student_name in defaulter_list -> Membership Operator.
bill_a is bill_c -> Identity Operator.

Arithmetic does the actual calculation of the bill. Comparison and Logical operators work together to take a decision (bonus or not) based on two conditions. Membership operator searches inside a list without using a loop. Assignment operator += helps update the bill in short form. So in one single real-world program, all operator types are used to complete a full business logic.

4. INPUTS & OUTPUTS:Taking inputs from the user and entering manually are names as inputs, whereas the result obtained after entering the input and executed as named as output of that particular program.
   

In [6]:
# INPUTS AND OUTPUTS- Mess Feedback System
print("--- Welcome to Hostel Mess Feedback Portal ---")
# 1. TAKING INPUTS
# input() function always takes data as string
student_name = input("Enter your Name: ") 
rating = int(input("Rate today's food from 1 to 5: ")) # converting str to int
days_present = int(input("How many days did you eat this month? "))

print("\n--- Processing your feedback... ---")

# 2. PROCESSING
base_bill = days_present * 100
discount = 0

if rating >= 4:
    discount = 200
    message = "Thank you for the great rating!"
elif rating >= 3:
    discount = 100
    message = "Thank you for your feedback!"
else:
    message = "We are sorry. We will improve."

final_bill = base_bill - discount

# 3. GIVING OUTPUTS
print("\n========== OUTPUT RECEIPT ==========")
print(f"Student Name: {student_name}") # Output 1
print(f"Days Present: {days_present}") # Output 2
print(f"Base Bill: {base_bill}") # Output 3
print(f"Discount Applied: {discount}") # Output 4
print(f"Final Bill to Pay: {final_bill}") # Output 5
print(f"Message: {message}") # Output 6
print("====================================")

--- Welcome to Hostel Mess Feedback Portal ---


Enter your Name:  mk
Rate today's food from 1 to 5:  4
How many days did you eat this month?  15



--- Processing your feedback... ---

========== OUTPUT RECEIPT ==========
Student Name: mk
Days Present: 15
Base Bill: 1500
Discount Applied: 200
Final Bill to Pay: 1300
Message: Thank you for the great rating!


part of the code demonstrates the concept: 
Input Part: input("Enter your Name: ") and int(input("Rate..."))  This is where the program stops and waits for the user to give data. input() is the main function for taking input.
Process Part: The if-elif-else and calculations like base_bill = days_present * 100  This is where input data is used to make decisions.
Output Part: All the print() statements  This is where the program shows the result back to the user.

Python runs only the actual code. Anything we write after # or inside """ """ for documentation is not executed. It is only for humans.
Why do we need it?
   Because code tells the computer what to do, but comments tell other humans why we did it. After 6 months, even you will forget why you wrote a line. Comments help you remember.
There are 3 types:
1. Single-line comment: Starts with #. Used for short notes on one line.
2. Multi-line comment: We use # on each line, or use """ """. Used for longer explanation.
3. Docstring: The string written at the start of a function/class with """ """. It is used to explain what that function does.

In [7]:
# Payroll Calculator with Comments
"""
This program calculates Net Salary for a hostel mess worker.
This multi-line comment explains the whole file purpose.
Author: Madhuri
Date: 2026
"""

# --- Input Section ---
# Taking basic inputs - these are fixed for this employee
basic_pay = 25000  # Fixed basic for this month (int)
# bonus is extra for festival, only for this month
bonus = 2000  # Festival bonus

# Calculation part
# Formula: Gross = basic + bonus
gross_salary = basic_pay + bonus  # Total before deductions

# Deductions - PF is 12% of basic
pf_deduction = basic_pay * 0.12  # Calculating 12% PF

# Final Calculation
net_salary = gross_salary - pf_deduction  # Net = Gross - PF

def print_payslip(name, net_pay):
    """
    Docstring (This is a special comment)
    This function prints the final payslip.
    It takes name and net salary as input.
    """
    # This line prints the final output
    print(f"Payslip for {name}: Net Salary is {net_pay}")

# Calling the function
print_payslip("Ramesh", net_salary)  # Ramesh is a mess worker

Payslip for Ramesh: Net Salary is 24000.0


basic_pay = 25000  # Fixed basic... -> This demonstrates Single-line Comment using #.
""" This program calculates... """ at the top -> This demonstrates Multi-line Comment explaining the whole file.def print_payslip...
""" Docstring """ -> This demonstrates Docstring which explains what a function does.Python will ignore all these comment lines and will only run the calculation and print lines.3. 

How the concept works in my implementation:
When I run this code, Python will skip every line starting with # and every text inside """ """. It will only execute basic_pay = 25000, gross_salary = ..., pf_deduction = ..., and print_payslip().

6. CONTROL FLOW:

Control Flow: Control Flow means deciding the route of the program.By default Python is like a straight road - it goes from top to bottom. 
Control Flow gives us turns and signals.
It has 3 main families: 
1. Decision Making - if / elif / else
This is for taking decisions. if = first condition check.elif = second condition check, only if first is false. You can have many elif.else = if nothing is true, do this. It's the last option.
2. Looping - for loop / while loop
This is for repeating work.for loop = when you know how many times to repeat. Example: For 10 employees, process each one.while loop = when you don't know how many times, but you repeat until a condition is true. Example: While salary file is not uploaded, keep trying.
3. Flow Controllers - break / continue / pass
This is for controlling the loop from inside.break = Stop the entire loop immediately and come out.continue = Skip only this one round and go to next round.pass = Do nothing. It's just a placeholder to avoid error when we will write code later.


In [9]:
# Control Flow - All Concepts in One Unique Example
# Topic: if/elif/else, for, while, break, continue, pass
print("=== Attendance Verification Started (for loop) ===\n")

# Employee list: name, punch time, leave status
# for loop concept - we know we have 5 employees
employees = [
    {"name": "Amit", "time": 9.15, "on_leave": False},
    {"name": "Sneha", "time": 10.15, "on_leave": False},
    {"name": "Ravi", "time": 0, "on_leave": True}, # On leave case - for continue
    {"name": "Priya", "time": 11.00, "on_leave": False},
    {"name": "Error", "time": 0, "on_leave": False}, # For break case
]

# --- FOR LOOP + IF/ELIF/ELSE + CONTINUE + BREAK + PASS ---
for emp in employees: # for loop - repeating for each employee
    
    # continue concept - skip if on leave
    if emp["on_leave"] == True:
        print(f"{emp['name']} is on Official Leave -> Skipping (continue used)")
        print("-" * 40)
        continue  # skip this iteration

    # break concept - stop everything if server error found
    if emp["name"] == "Error":
        print("Biometric Server Down! Stopping verification (break used)")
        break  # stop entire loop

    # if / elif / else concept - decision making
    print(f"Checking for: {emp['name']}, Punch Time: {emp['time']}")
    
    if emp["time"] <= 9.30 and emp["time"] != 0:
        status = "On Time"
        print(f"if condition true -> {status}")
    
    elif emp["time"] <= 10.30:
        status = "Late"
        print(f"elif condition true -> {status}")

    else:
        status = "Absent / Half Day"
        print(f"else condition true -> {status}")

    # pass concept - placeholder for future logic
    if status == "On Time":
        pass  # Reward logic will be added next month, so using pass for now
        print("Pass used: Reward logic pending\n")
    else:
        print("No reward\n")

print("\n=== Server Reconnection - while loop demonstration ===")

# --- WHILE LOOP CONCEPT ---
# while loop - when we don't know how many attempts
attempt = 1
server_connected = False

while server_connected == False: # keep looping until condition becomes True
    print(f"Attempt {attempt}: Trying to connect to server...")
    
    if attempt == 3: # assume server connects on 3rd attempt
        server_connected = True
        print("Server Connected Successfully on 3rd attempt!")
    else:
        print("Failed, will retry...")
    
    attempt = attempt + 1 # important to avoid infinite loop

print("\n=== Verification Process Completed ===")

=== Attendance Verification Started (for loop) ===

Checking for: Amit, Punch Time: 9.15
if condition true -> On Time
Pass used: Reward logic pending

Checking for: Sneha, Punch Time: 10.15
elif condition true -> Late
No reward

Ravi is on Official Leave -> Skipping (continue used)
----------------------------------------
Checking for: Priya, Punch Time: 11.0
else condition true -> Absent / Half Day
No reward

Biometric Server Down! Stopping verification (break used)

=== Server Reconnection - while loop demonstration ===
Attempt 1: Trying to connect to server...
Failed, will retry...
Attempt 2: Trying to connect to server...
Failed, will retry...
Attempt 3: Trying to connect to server...
Server Connected Successfully on 3rd attempt!

=== Verification Process Completed ===


for emp in employees: 
-> for loop - Because we know the total number of employees.if / elif / else: 
-> Decision Making - To decide On Time, Late, Absent based on punch time.continue 
-> Skips Ravi who is on leave, goes directly to next employee.break 
-> Stops everything when "Error" employee found (server down).pass 
-> Used when status is On Time, as reward logic will be added later, so we keep it as placeholder.while server_connected == False: 
-> while loop - Repeats connection attempts until server connects. We don't know how many attempts it will take.

7. COLLECTIONS:

Collections are like different types of boxes to store multiple values together. In Python we have 4 main collections.
1. List: A list is an ordered, changeable box. We can add, remove, update values. It allows duplicate values. Created with [].
   Example: [25000][30000][25000] - salaries of employees. List is mutable, meaning we can change it after creation.
   
2. Tuple: Tuple is also ordered, but it is unchangeable (immutable). Once created, we cannot add or remove. Created with (). It also allows duplicates.
   Example: ("Vijayawada", "Andhra Pradesh", "522007") - permanent address. Tuple is faster and safer for fixed data.

   
3. Set: Set is an unordered box with no duplicates. It automatically removes duplicate values. It is changeable, but we cannot access by index because    it has no order. Created with {}.
   Example: {"HR", "Payroll", "HR"} will become {"HR", "Payroll"}. Used when we need unique values.

   
4. Dictionary: Dictionary is a key-value box. Instead of index numbers, we use names (keys) to store values. It is ordered and changeable, and no         duplicate keys. Created with {key: value}.
   Example: {"name": "Madhuri", "salary": 25000}. This is best for real-world records.
5. List Comprehension: A short and smart way to create a new list from an old list in one line. Instead of writing 3 lines of for loop, we write one line. Format: [expression for item in old_list if condition].

   
6. Dictionary Comprehension: Same smart way but for dictionary. Creates new dictionary from old data in one line. Format: {key: expression for item in old_list}.

In [11]:
# Collections - list, tuple, set, dictionary, comprehensions
print("=== Collections in Python - Payroll Example ===\n")

# 1. LIST - ordered, mutable, allows duplicate
# Employee salaries - we can change, add, duplicate allowed
salary_list = [25000, 30000, 28000, 25000, 45000]
print(f"1. LIST (salary_list): {salary_list}")
# List is mutable - we can add new salary
salary_list.append(32000)
print(f" After adding new salary: {salary_list}")

# 2. TUPLE - ordered, immutable, allows duplicate
# Company location - fixed, cannot change
company_address = ("RazorpayX", "Vijayawada", "522007")
print(f"\n2. TUPLE (company_address): {company_address}")
# company_address[0] = "New" # This will give error - tuple cannot be changed

# 3. SET - unordered, mutable, NO duplicate
# Departments - we want only unique names
departments = {"Payroll", "HR", "Finance", "Payroll", "HR", "IT"}
print(f"\n3. SET (departments): {departments} - Duplicates removed automatically")

# 4. DICTIONARY - key:value, ordered, mutable, no duplicate keys
# One employee record with labels
employee_dict = {
    "name": "Madhuri",
    "id": 101,
    "salary": 25000,
    "dept": "Payroll"
}
print(f"\n4. DICTIONARY (employee_dict): {employee_dict}")
print(f" Accessing salary by key: {employee_dict['salary']}")

# 5. LIST COMPREHENSION - smart way to create list
# Task: Get only high salaries > 30000 from salary_list
# Normal way needs 3-4 lines, comprehension does in 1 line
high_salaries = [sal for sal in salary_list if sal > 30000]
print(f"\n5. LIST COMPREHENSION (salaries > 30000): {high_salaries}")
# Another example: Add 2000 bonus to all
with_bonus = [sal + 2000 for sal in salary_list]
print(f" After 2000 bonus added (comprehension): {with_bonus}")

# 6. DICTIONARY COMPREHENSION - smart way to create dict
# Task: Create dict of name:bonus from employee names
employee_names = ["Amit", "Sneha", "Ravi"]
# Create bonus dict where bonus = len(name)*1000
bonus_dict = {name: len(name)*1000 for name in employee_names}
print(f"\n6. DICTIONARY COMPREHENSION (name:bonus): {bonus_dict}")

# Extra: Dict comprehension from salary_list
# Create dict of salary:PF where PF is 12%
pf_dict = {sal: sal*0.12 for sal in set(salary_list)} # using set to avoid duplicate salary
print(f" PF Dictionary (salary:pf): {pf_dict}")

=== Collections in Python - Payroll Example ===

1. LIST (salary_list): [25000, 30000, 28000, 25000, 45000]
 After adding new salary: [25000, 30000, 28000, 25000, 45000, 32000]

2. TUPLE (company_address): ('RazorpayX', 'Vijayawada', '522007')

3. SET (departments): {'Payroll', 'Finance', 'HR', 'IT'} - Duplicates removed automatically

4. DICTIONARY (employee_dict): {'name': 'Madhuri', 'id': 101, 'salary': 25000, 'dept': 'Payroll'}
 Accessing salary by key: 25000

5. LIST COMPREHENSION (salaries > 30000): [45000, 32000]
 After 2000 bonus added (comprehension): [27000, 32000, 30000, 27000, 47000, 34000]

6. DICTIONARY COMPREHENSION (name:bonus): {'Amit': 4000, 'Sneha': 5000, 'Ravi': 4000}
 PF Dictionary (salary:pf): {32000: 3840.0, 28000: 3360.0, 25000: 3000.0, 45000: 5400.0, 30000: 3600.0}


8. FUNCTIONS:

A Function is when we create once and use many times. Instead of writing same calculation again and again, we pack it inside a function and call it when needed. We define it with def

Company Payroll Department:

Think of Payroll Dept as Functions:
Function Definition: You create a separate section "Salary Calculation Dept" - you define it once.Arguments: You give them Basic Pay as input to calculate.
Default Arguments: If you don't tell bonus, they by default give 2000 festival bonus to everyone.
Keyword Arguments: You can send details as name="Amit", dept="HR" - order doesn't matter._
args: You say "deduct PF, TDS, Loan" - you don't know how many deductions, they accept all.
_\kwargs:* You give extra employee info like location="Vijayawada", shift="Night" - they accept any extra info as a list.
Lambda: For a very small quick calculation like PF = 12%, you don't create a full dept, you just use a calculator on table.
Recursive: To calculate total yearly salary, you ask "this month salary + rest of the months salary". The function calls itself for remaining months until 1 month left.

In [10]:
# Functions - All Concepts - Unique Example
print("=== Payroll Function System ===\n")

# 1. Function Definition + Arguments + Default Arguments
# bonus=2000 is Default Argument. If not given, 2000 will be used.
def calculate_gross(basic, bonus=2000):
    """This function shows Definition, Arguments, Default Arguments"""
    gross = basic + bonus
    print(f"[Gross Function] Basic {basic} + Bonus {bonus} = Gross {gross}")
    return gross

# 2. Variable-Length Arguments (*args) - for unknown deductions
def calculate_net(gross, *args):
    """*args collects all deductions - PF, TDS, Loan etc"""
    print(f"[Net Function] Gross is {gross}, Deductions received (args): {args}")
    total_deduction = sum(args) # args is a tuple
    net = gross - total_deduction
    return net

# 3. Keyword Arguments + **kwargs - for extra employee info
def print_payslip(name, net_salary, **kwargs):
    """Keyword args and **kwargs for extra details"""
    print(f"\n--- Payslip for {name} ---")
    print(f"Net Salary: {net_salary}")
    # kwargs is a dictionary
    for key, value in kwargs.items():
        print(f"{key}: {value}")

# 4. Lambda Function - small one-line function
# Quick PF calculation
pf_calculate = lambda basic: basic * 0.12
print(f"[Lambda Function] PF for 25000 is: {pf_calculate(25000)}")

# 5. Recursive Function - calls itself
def total_salary_recursive(months, per_month_salary):
    """Recursive: total salary for N months"""
    # Base condition to stop recursion
    if months == 1:
        return per_month_salary
    else:
        # Function calls itself
        return per_month_salary + total_salary_recursive(months - 1, per_month_salary)

# --- Calling / Using all functions ---

# Calling with Default Argument (bonus not given, so 2000 default will be used)
gross1 = calculate_gross(25000) 

# Calling with Keyword Arguments (order changed)
gross2 = calculate_gross(bonus=5000, basic=30000) 

# Using *args - giving 3 deductions at once
net_pay = calculate_net(gross1, 3000, 1500, 500) # 3000=PF, 1500=TDS, 500=Loan

# Using **kwargs - giving extra info like department, location
# This also shows Keyword Arguments
print_payslip("Madhuri", net_pay, Department="Payroll", Location="Vijayawada", Month="Oct")

# Using Recursion
yearly_total = total_salary_recursive(3, 25000) # 3 months * 25000
print(f"\n[Recursive Function] Total salary for 3 months: {yearly_total} (25000+25000+25000)")

=== Payroll Function System ===

[Lambda Function] PF for 25000 is: 3000.0
[Gross Function] Basic 25000 + Bonus 2000 = Gross 27000
[Gross Function] Basic 30000 + Bonus 5000 = Gross 35000
[Net Function] Gross is 27000, Deductions received (args): (3000, 1500, 500)

--- Payslip for Madhuri ---
Net Salary: 22000
Department: Payroll
Location: Vijayawada
Month: Oct

[Recursive Function] Total salary for 3 months: 75000 (25000+25000+25000)


Code part demonstrates the concept:
def calculate_gross(basic, bonus=2000): 
-> Function Definition (def), Arguments (basic), Default Arguments (bonus=2000).calculate_gross(bonus=5000, basic=30000) 
-> Keyword Arguments - I passed by name, order changed.def calculate_net(gross, _args): 
-> Variable-Length _args - It accepted 3 deductions (3000, 1500, 500) as tuple.def print_payslip(name, net_salary, *kwargs):
-> Variable-Length *kwargs - It accepted Department, Location, Month as dictionary.pf_calculate = lambda basic: basic _ 0.12 
-> Lambda Function - One-line small function for PF.def total_salary_recursive calling itself total_salary_recursive(months - 1, ...) -> Recursive Function.

Advanced Python:

ITERATIONS:

Iteratons are used to repeat same line of code for multiple times, until the given condition satisfies.

Iterable: The object that holds items and can be looped. Example: list, string, tuple. [10, 20, 30] is iterable.
    Iterator: The helper that takes out one item at a time from the iterable. Created by iter().
    Iteration: The process of looping. for loop does it automatically.iter() + next() does it manually.

In [12]:
# Iterations
# Iterable - small list with 3 numbers
nums = [10, 20, 30]
print(f"Iterable: {nums}\n")

# 1. Automatic Iteration - for loop
print("1. For Loop (Automatic):")
for n in nums:
    print(f"  Value: {n}")

# 2. Manual Iteration - iter() and next()
print("\n2. Manual (iter + next):")
it = iter(nums) # create iterator

print(f"  next(it) -> {next(it)}") # gives 10
print(f"  next(it) -> {next(it)}") # gives 20
print(f"  next(it) -> {next(it)}") # gives 30
# next(it) now will give StopIteration because list over

# 3. Iterating on String - smallest iterable
print("\n3. String Iteration:")
for ch in "Hi":
    print(f"  Char: {ch}")

Iterable: [10, 20, 30]

1. For Loop (Automatic):
  Value: 10
  Value: 20
  Value: 30

2. Manual (iter + next):
  next(it) -> 10
  next(it) -> 20
  next(it) -> 30

3. String Iteration:
  Char: H
  Char: i


 part demonstrates the concept:nums = [10,20,30] -> 
 Iterable - the box.for n in nums: -> 
 Iteration (Automatic) - for loop.it = iter(nums) ->
 Iterator - creation of hand.next(it) -> 
 Manual Iteration - picks one by one.for ch in "Hi": -> Shows string is also iterable.

In [13]:
# Generators:

print("=== Generators in Python ===\n")

# 1. Generator Function - using yield
# This generates bonus one by one
def bonus_generator(salary_list):
    print("[Generator Function Started]")
    for sal in salary_list:
        bonus = sal * 0.10 # 10% bonus
        print(f"  Calculating bonus for {sal}...")
        yield bonus  # yield - gives one value and pauses
    print("[Generator Finished]")

# Our small iterable
salaries = [25000, 30000, 28000]
print(f"Salary List: {salaries}\n")

# Create generator object - it does NOT run yet, it's lazy
gen = bonus_generator(salaries)
print(f"Generator Object Created: {gen}")
print("It has not calculated anything yet - lazy!\n")

# Now ask for values one by one using next()
print("Method 1: Manual with next():")
print(f"  next(gen) -> {next(gen)}") # First yield - gives 2500 and pauses
print(f"  next(gen) -> {next(gen)}") # Continues - gives 3000
print(f"  next(gen) -> {next(gen)}") # Gives 2800

# Uncomment to see StopIteration
# print(next(gen)) # No more values -> StopIteration error

print("\nMethod 2: Automatic with for loop (creates new generator):")
# for loop automatically calls next() till over
for b in bonus_generator(salaries):
    print(f"  Bonus received: {b}")

# 2. Generator Expression - like list comprehension but with ()
print("\nMethod 3: Generator Expression (one line):")
# This is same as list comprehension but with () - saves memory
gen_exp = (sal + 2000 for sal in salaries) # ( ) not [ ]
print(f"Generator Expression Object: {gen_exp}")

for val in gen_exp:
    print(f"  Salary with extra 2000: {val}")

# 3. Proof - Memory Saving
print("\nMethod 4: Why Generator is better?")
import sys
list_comp = [sal*0.10 for sal in salaries] # stores all
gen_comp = (sal*0.10 for sal in salaries) # generates one by one
print(f"List size (stores all): {sys.getsizeof(list_comp)} bytes")
print(f"Generator size (one by one): {sys.getsizeof(gen_comp)} bytes - Much Smaller!")

=== Generators in Python ===

Salary List: [25000, 30000, 28000]

Generator Object Created: <generator object bonus_generator at 0x000001ABCB459F30>
It has not calculated anything yet - lazy!

Method 1: Manual with next():
[Generator Function Started]
  Calculating bonus for 25000...
  next(gen) -> 2500.0
  Calculating bonus for 30000...
  next(gen) -> 3000.0
  Calculating bonus for 28000...
  next(gen) -> 2800.0

Method 2: Automatic with for loop (creates new generator):
[Generator Function Started]
  Calculating bonus for 25000...
  Bonus received: 2500.0
  Calculating bonus for 30000...
  Bonus received: 3000.0
  Calculating bonus for 28000...
  Bonus received: 2800.0
[Generator Finished]

Method 3: Generator Expression (one line):
Generator Expression Object: <generator object <genexpr> at 0x000001ABCB5EB850>
  Salary with extra 2000: 27000
  Salary with extra 2000: 32000
  Salary with extra 2000: 30000

Method 4: Why Generator is better?
List size (stores all): 88 bytes
Generator 

Code part demonstrates the concept:def bonus_generator(salary_list): ... yield bonus 
->Generator Function - function with yield instead of return.gen = bonus_generator(salaries) 
-> Generator Object - created but not executed yet, proves lazy nature.next(gen) 
-> yield working - gives one value, pauses, remembers state, next call continues.(sal + 2000 for sal in salaries) 
-> Generator Expression - one-line generator with () not [].for b in bonus_generator(...): 
-> Shows generator is iterable and for loop calls next() automatically.

YIELD:

The YIELD keyword is used to turn a standard function into a generator function.
Pauses the function and saves its state.
Produces a stream/sequence of values over time.
Low memory usage; generates data "lazily" on the fly.
Continues from the exact line where it paused.

In [14]:
# Yield - Very Small & Unique Example
def id_generator():
    print("Generator started")
    yield "EMP101"  # Give 1st ID and PAUSE
    print("Resumed after 101")
    yield "EMP102"  # Give 2nd ID and PAUSE
    print("Resumed after 102")
    yield "EMP103"  # Give 3rd ID and PAUSE
    print("Generator finished")

# Create generator - no code runs yet (lazy)
gen = id_generator()
print(f"Created: {gen}\n")

# Get IDs one by one
print(f"1st next() -> {next(gen)}")
print(f"2nd next() -> {next(gen)}")
print(f"3rd next() -> {next(gen)}")

Created: <generator object id_generator at 0x000001ABCB46FF40>

Generator started
1st next() -> EMP101
Resumed after 101
2nd next() -> EMP102
Resumed after 102
3rd next() -> EMP103


How the Program works:
It generates 3 employee IDs EMP101, EMP102, EMP103 one by one using yield. It proves pause/resume.

yield "EMP101" -> Core concept - gives one ID and pauses, remembers.
gen = id_generator() -> No code run yet, only generator object created - lazy nature of yield.next(gen) -> First call runs till first yield and pauses, second call resumes from there, proves memory of yield.

DECORATORS:

Decorator is a function that adds extra features to another function without changing its original code.
In Python, functions are first-class objects - we can pass a function as argument, return a function, and define a function inside another function. Decorator uses this property.
A decorator has 3 parts:
It takes another function as input.It creates an inner wrapper function that adds some code before and after the original function.It returns the wrapper function.We use @decorator_name on top of a function.

In [15]:
# Decorator:

def badge_decorator(func):
    def wrapper(name):
        print("--- Badge START ---")
        func(name)  # Call original
        print("--- Badge END ---")
    return wrapper

@badge_decorator
def print_name(name):
    print(f"Name: {name}")

# Calling
print_name("Madhuri")

--- Badge START ---
Name: Madhuri
--- Badge END ---


print_name only prints name. 
Decorator badge_decorator adds Badge START and Badge END lines around it.
2. Which part demonstrates concept:def badge_decorator(func): -> Takes function as input = Decorator.def wrapper(name): -> Adds extra lines before and after func(name).return wrapper -> Returns decorated function.@badge_decorator -> Applies decorator to print_name.

CLOSURES:

Closure is a function that remembers values from its outer function even after the outer function has finished.
when outer function ends, its variables are destroyed. But if inner function is returned, Python keeps those outer variables alive in memory. Inner function carries them like a backpack. That backpack is called Closure.

Closure = Inner function + Remembered outer variables.

GLOBAL & NONLOCAL:

LOCAL VARIABLE:
Variable inside a function. Only that function can use it.

GLOBAL VARIABLE:
Variable outside all functions. All functions can read it, but cannot change it unless you say global.

NONLOCAL VARIABLE: Nonlocal Variable is also called as Enclosing variable, When one function is inside another. Inner function can read outer function's variable, but cannot change it unless you say nonlocal.

In [16]:
# Office Bonus Counter using Global and Nonlocal
# Global & Nonlocal:

print("=== Global & Nonlocal ===\n")

# Global variable - outside all functions
total_bonus_given = 0

def salary_department(emp_name):
    # Enclosing variable - inside outer, outside inner
    dept_bonus = 0

    def give_bonus(amount):
        nonlocal dept_bonus  # Means use outer function's dept_bonus
        global total_bonus_given # Means use global total_bonus_given

        dept_bonus += amount
        total_bonus_given += amount

        print(f"Gave {amount} to {emp_name}. Dept bonus = {dept_bonus}, Total = {total_bonus_given}")

    print(f"\n-- Department for {emp_name} --")
    print(f"Before: dept_bonus={dept_bonus}, total={total_bonus_given}")

    give_bonus(1000)
    give_bonus(2000)

    print(f"After: dept_bonus={dept_bonus}, total={total_bonus_given}")

# Call for 2 employees
salary_department("Madhuri")
salary_department("Raju")

print(f"\nFinal Global Total Bonus = {total_bonus_given}")

# What happens without global/nonlocal?
print("\n--- Without global/nonlocal (problem) ---")
count = 0
def try_change():
    count = 10  # This creates NEW local count, not global
    print(f"Inside function local count = {count}")

try_change()
print(f"Outside global count still = {count} -> Not changed!")

=== Global & Nonlocal ===


-- Department for Madhuri --
Before: dept_bonus=0, total=0
Gave 1000 to Madhuri. Dept bonus = 1000, Total = 1000
Gave 2000 to Madhuri. Dept bonus = 3000, Total = 3000
After: dept_bonus=3000, total=3000

-- Department for Raju --
Before: dept_bonus=0, total=3000
Gave 1000 to Raju. Dept bonus = 1000, Total = 4000
Gave 2000 to Raju. Dept bonus = 3000, Total = 6000
After: dept_bonus=3000, total=6000

Final Global Total Bonus = 6000

--- Without global/nonlocal (problem) ---
Inside function local count = 10
Outside global count still = 0 -> Not changed!


Code part demonstrates the concept:total_bonus_given = 0 at top 
-> Global variable.dept_bonus = 0 inside salary_department 
-> Enclosing variable.nonlocal dept_bonus 
-> Nonlocal concept - tells inner function to use outer's dept_bonus, not create new local. So dept_bonus keeps increasing to 1000 then 3000.global total_bonus_given 
-> Global concept - tells inner function to use global total, not create new local. So global keeps increasing to 6000 across all employees.Last part without keywords 
-> Shows problem, global stays 0, proving need of global.

MODULES:

Module is a Python file that contains Python code - functions, variables, classes - which we can use in another file.

Module is Reusable
It has Clean code - Small files easy to maintain.
Sharing - Others can use your module.

In [1]:
# Unique module for salary bonus

company_name = "Tech Solutions"

def calculate_bonus(salary):
    return salary * 0.10

def calculate_total(salary):
    return salary + calculate_bonus(salary)

In [ ]:
print("=== Modules in Python ===\n")

# Importing our own created module - this is the concept
import emp_bonus  # importing file emp_bonus.py

# Also importing built-in module for comparison
import math
print(math.sqrt(25))

print("1. Using my own module emp_bonus:")
print(f"Company: {emp_bonus.company_name}")
sal = 30000
print(f"Salary: {sal}")
print(f"Bonus: {emp_bonus.calculate_bonus(sal)}")
print(f"Total: {emp_bonus.calculate_total(sal)}")

print("\n2. Using built-in module math:")
print(f"Square root of 16: {math.sqrt(16)}")

print("\n3. Different way to import:")
from emp_bonus import calculate_bonus as cb
print(f"Bonus with from import: {cb(50000)}")

# Shows that module is an object
print(f"\nModule object: {emp_bonus}")
print(f"Module file path: {emp_bonus.__file__}")

emp_bonus.py file itself -> Is a Module - any Python file is a module.import emp_bonus -> Using Module - importing my own file.emp_bonus.calculate_bonus(sal) -> Accessing module's function with dot.import math and from emp_bonus import calculate_bonus as cb -> Shows built-in module and different import styles.emp_bonus.*file* -> Proves module is loaded from a file path.

PACKAGES:

package is a folder that contains many Python files (modules).
One Python file like bonus.py = ModuleOne folder containing many files like salary/ folder with bonus.py, tax.py = Package
Creating many files inside a single folder which are related to that same category are said to be PACKAGES. 

In [9]:
# CELL 1: Creating Package Structure - Run this first
import os

# Create package folder
os.makedirs("my_company", exist_ok=True)

# 1. Create __init__.py - This makes it a package
with open("my_company/__init__.py", "w") as f:
    f.write('''# __init__.py - Makes folder a package
print("my_company package loaded!")
company_name = "Tech Solutions"
''')

# 2. Create bonus.py - Module 1 inside package
with open("my_company/bonus.py", "w") as f:
    f.write('''# bonus.py
def calculate_bonus(salary):
    return salary * 0.10
''')

# 3. Create total.py - Module 2 inside package
with open("my_company/total.py", "w") as f:
    f.write('''# total.py
from .bonus import calculate_bonus
def calculate_total(salary):
    return salary + calculate_bonus(salary)
''')

print("Package my_company created successfully with 3 files!")
print("Files:", os.listdir("my_company"))

Package my_company created successfully with 3 files!
Files: ['bonus.py', 'total.py', '__init__.py']


In [10]:
# CELL 2: Using Package - Run after Cell 1
print("=== Packages in Python ===\n")

# Way 1: import package.module
import my_company.bonus
print("1. import package.module")
print(f"   Bonus for 30000 = {my_company.bonus.calculate_bonus(30000)}")

# Way 2: from package import module
from my_company import total
print("\n2. from package import module")
print(f"   Total for 30000 = {total.calculate_total(30000)}")

# Way 3: from package.module import function
from my_company.bonus import calculate_bonus as cb
print("\n3. from package.module import function")
print(f"   Bonus for 50000 = {cb(50000)}")

# Access variable from __init__.py
import my_company
print(f"\n4. From __init__.py: Company = {my_company.company_name}")

=== Packages in Python ===

my_company package loaded!
1. import package.module
   Bonus for 30000 = 3000.0

2. from package import module
   Total for 30000 = 33000.0

3. from package.module import function
   Bonus for 50000 = 5000.0

4. From __init__.py: Company = Tech Solutions


Code demonstrates the concept:

my_company/ folder with *init*.py -> This is Package. The folder + *init*.py proves it is a package.bonus.py and total.py inside my_company/ -> Modules inside Package.import my_company.bonus -> Dot notation which is the main concept of package.from .bonus import calculate_bonus in total.py -> Intra-package import, one module using another module from same package.

VIRTUAL ENVIRONMENTS:

Virtual Environment is a separate, isolated folder that has its own Python and its own packages.

1. Isolation - Packages of one project don't affect other project.
2. No version conflict - Different projects can use different versions of same library.
3. Clean system - Your main Python stays clean.

In [11]:
# CELL 1: Understanding main Python vs venv
import sys
import os

print("=== Virtual Environment Concept ===\n")

# 1. Show current main python path
print("1. My Main Python (System Python):")
print(f" Path: {sys.executable}")
print(f" Version: {sys.version.split()[0]}")

# 2. Create a new virtual environment named 'my_project_env'
# This is the main command: python -m venv my_project_env
print("\n2. Creating Virtual Environment 'my_project_env'...")
!python -m venv my_project_env
print(" Created!")

# 3. Show what is inside venv folder
print("\n3. Inside venv folder:")
print(os.listdir("my_project_env"))
print("Files in Scripts/bin:", os.listdir("my_project_env/Scripts")[:5], "...")

# 4. Show venv has its own python
print("\n4. Venv has its own separate Python:")
if os.name == 'nt': # Windows
    venv_python = "my_project_env\\Scripts\\python.exe"
    venv_pip = "my_project_env\\Scripts\\pip.exe"
else:
    venv_python = "my_project_env/bin/python"
    venv_pip = "my_project_env/bin/pip"

print(f" Main python: {sys.executable}")
print(f" Venv python: {os.path.abspath(venv_python)}")
print(" -> Two different pythons! This is isolation.")

=== Virtual Environment Concept ===

1. My Main Python (System Python):
 Path: C:\Users\Admin\anaconda3\python.exe
 Version: 3.14.6

2. Creating Virtual Environment 'my_project_env'...
 Created!

3. Inside venv folder:
['.gitignore', 'Include', 'Lib', 'pyvenv.cfg', 'Scripts']
Files in Scripts/bin: ['activate', 'activate.bat', 'activate.fish', 'Activate.ps1', 'deactivate.bat'] ...

4. Venv has its own separate Python:
 Main python: C:\Users\Admin\anaconda3\python.exe
 Venv python: C:\Users\Admin\my_project_env\Scripts\python.exe
 -> Two different pythons! This is isolation.


In [ ]:
# CELL 2: Prove that venv is isolated
print("=== Proving Isolation ===\n")

# Check pip list in MAIN python
print("1. Packages in MAIN Python:")
!pip list | findstr pandas
# For Mac/Linux use:!pip list | grep pandas

# Check pip list in VENV python (it will be empty/new)
print("\n2. Packages in VENV Python (Fresh & Empty):")
if os.name == 'nt':
   !my_project_env\Scripts\pip.exe list
else:
   !my_project_env/bin/pip list

print("\n3. Installing a package ONLY in venv:")
if os.name == 'nt':
   !my_project_env\Scripts\pip.exe install requests --quiet
    print(" Installed 'requests' in venv only")
   !my_project_env\Scripts\pip.exe list | findstr requests
else:
   !my_project_env/bin/pip install requests --quiet
    print(" Installed 'requests' in venv only")
   !my_project_env/bin/pip list | grep requests

print("\n4. Checking MAIN python - requests is NOT there (if not installed before):")
!pip show requests

In [ ]:
# CELL 3: Show commands - Write this as steps in your assignment
print("""
=== How to use Virtual Environment in VS Code / Terminal ===

Step 1: Create venv
> python -m venv myenv

Step 2: Activate venv
Windows: > myenv\\Scripts\\activate
Mac/Linux: > source myenv/bin/activate

After activate, you see (myenv) in terminal:
(myenv) C:\\Projects>

Step 3: Now install packages - they go inside venv only
(myenv) > pip install pandas==1.0

Step 4: Work on project...

Step 5: Deactivate when done
(myenv) > deactivate

Step 6: To delete venv, just delete folder myenv
""")

# Show unique code - using venv python to run a script
with open("test_in_venv.py", "w") as f:
    f.write('import sys\nprint(f"Hello from VENV! Python at: {sys.executable}")\n')

print("\nRunning same script with two different pythons:")
print("Main python runs:")
!python test_in_venv.py
print("\nVenv python runs:")
if os.name == 'nt':
   !my_project_env\Scripts\python.exe test_in_venv.py
else:
   !my_project_env/bin/python test_in_venv.py

 part of the code demonstrates the concept:
!python -m venv my_project_env 
     -> Creates Virtual Environment - core concept.sys.executable vs my_project_env\Scripts\python.exe
     -> Two different Pythons, shows isolation.my_project_env\Scripts\pip.exe list vs pip list 
     -> Different package lists, proves venv is separate.pip install inside venv only 
     -> Package installed in venv does not affect main.

TYPE HINTING:

Python normally does not need types. You can write x = 10 and later x = "hello", it works. This is called dynamic typing.

Type hints are only hints. Python does NOT stop you if you give wrong type. It will still run. Hints are for humans and for tools like VS Code, PyCharm, mypy to show errors before running.

Generally, TYPE HINTING helps in big projects - other developers can see what type to pass without reading full function.

In [19]:
# CELL 1: Basic Type Hinting
print("=== Type Hinting in Python ===\n")

# Without type hinting (normal python)
name = "Madhuri"
age = 21

# With type hinting (with label)
name_typed: str = "Madhuri"
age_typed: int = 21
salary_typed: float = 30000.50
is_employee_typed: bool = True

print(f"Name: {name_typed}, Age: {age_typed}")
print("This is basic variable type hinting - name: str means name should be string")

# Function without hint
def add(a, b):
    return a + b

# Function WITH type hint
def add_typed(a: int, b: int) -> int:
    # a: int means a should be int, b: int means b should be int, -> int means return should be int
    return a + b

print(f"\nAdd without hint: {add(10, 20)}")
print(f"Add with hint: {add_typed(10, 20)}")

# Even if we pass wrong type, Python still runs (hints are not strict)
print(f"Wrong type still runs: {add_typed('hi', 'hello')} # Hint says int but we gave str, still works")

=== Type Hinting in Python ===

Name: Madhuri, Age: 21
This is basic variable type hinting - name: str means name should be string

Add without hint: 30
Add with hint: 30
Wrong type still runs: hihello # Hint says int but we gave str, still works


In [20]:
# CELL 2: Unique Example - Employee Bonus System with Type Hints
from typing import List, Dict, Optional, Union

# Custom function with all type hints
def calculate_bonus(salary: float, percentage: float = 10.0) -> float:
    """salary should be float, percentage float, returns float"""
    return salary * (percentage / 100)

def get_employee_names(employees: List[Dict[str, Union[str, int]]]) -> List[str]:
    """Takes list of dicts, returns list of strings"""
    names = []
    for emp in employees:
        names.append(emp["name"]) # type: ignore
    return names

def find_employee(emp_id: int, employees: List[Dict]) -> Optional[Dict]:
    """Returns dict or None if not found"""
    for emp in employees:
        if emp["id"] == emp_id:
            return emp
    return None

# Using it
employees_data: List[Dict] = [
    {"id": 1, "name": "Madhuri", "salary": 30000},
    {"id": 2, "name": "Ravi", "salary": 40000}
]

print("Employees:", get_employee_names(employees_data))
print(f"Bonus for 30000: {calculate_bonus(30000.0)}")
print(f"Bonus for 30000 with 15%: {calculate_bonus(30000.0, 15.0)}")

emp: Optional[Dict] = find_employee(1, employees_data)
print(f"Found employee 1: {emp}")

emp_not_found: Optional[Dict] = find_employee(99, employees_data)
print(f"Employee 99: {emp_not_found}")

Employees: ['Madhuri', 'Ravi']
Bonus for 30000: 3000.0
Bonus for 30000 with 15%: 4500.0
Found employee 1: {'id': 1, 'name': 'Madhuri', 'salary': 30000}
Employee 99: None


In [21]:
# CELL 3: Type Hinting helps IDE to catch errors
# In VS Code / PyCharm, this would show red underline

def greet(name: str) -> str:
    return f"Hello {name}"

# Correct usage - IDE shows OK
print(greet("Madhuri"))

# Wrong usage - IDE will warn you, but Python still runs
# In Jupyter it runs, but mypy tool would show error
print(greet(12345)) # We passed int but hint says str

# Example with list and dict hints
def total_salary(salaries: List[float]) -> float:
    return sum(salaries)

my_salaries: List[float] = [30000.0, 40000.0, 50000.0]
print(f"\nTotal salary: {total_salary(my_salaries)}")

# Dict type hint
employee_dict: Dict[str, Union[str, int, float]] = {
    "name": "Madhuri",
    "age": 21,
    "salary": 30000.50
}
print(f"Employee Dict: {employee_dict}")

Hello Madhuri
Hello 12345

Total salary: 120000.0
Employee Dict: {'name': 'Madhuri', 'age': 21, 'salary': 30000.5}


part of the code demonstrates the concept:
name_typed: str = "Madhuri" -> Variable type hinting.def add_typed(a: int, b: int) 
-> int: 
-> Function argument and return type hinting. 
-> int shows function should return int.List[Dict], Optional[Dict], Union[str][int] 
-> Complex type hinting for list, dict that may be None or multiple types.calculate_bonus(salary: float, percentage: float = 10.0)
-> float -> Shows hint works with default values also.

BUILT- IN - FUNCTIONS:

MAP():

map() is a built-in function in Python that applies a function to EVERY item in a list or iterable.

Key points:
1. It does NOT change original list,
2. it creates new result.
3. It is faster and shorter than for loop.
4. We often use it with lambda (small one-line function) or normal function.
5. It can take multiple iterables also: map(lambda x, y: x+y, list1, list2).
   In simple words, map() can simplifieses the code from many lines to few lines.

In [22]:
# CELL 1: Basic map()
print("=== map() Built-in Function ===\n")

# Example 1: Without map() - using loop
salaries = [30000, 40000, 50000]
print("Original salaries:", salaries)

bonus_loop = []
for sal in salaries:
    bonus_loop.append(sal * 0.10)

print("Bonus with for loop:", bonus_loop)

# Same with map() - One line
def calc_bonus(sal):
    return sal * 0.10

bonus_map = list(map(calc_bonus, salaries))
print("Bonus with map():  ", bonus_map)

print("\n--- map() with lambda (more short) ---")
# lambda is one line function: lambda argument: operation
bonus_lambda = list(map(lambda sal: sal * 0.10, salaries))
print("Bonus with map+lambda:", bonus_lambda)

print("\nmap() returns map object, we need list() to see it:")
result_obj = map(lambda x: x*0.10, salaries)
print("Direct map object:", result_obj)
print("After list():", list(result_obj))

=== map() Built-in Function ===

Original salaries: [30000, 40000, 50000]
Bonus with for loop: [3000.0, 4000.0, 5000.0]
Bonus with map():   [3000.0, 4000.0, 5000.0]

--- map() with lambda (more short) ---
Bonus with map+lambda: [3000.0, 4000.0, 5000.0]

map() returns map object, we need list() to see it:
Direct map object: <map object at 0x000001E6881F8340>
After list(): [3000.0, 4000.0, 5000.0]


In [23]:
# CELL 2: Unique Example - Employee Data Processing

# My data: Employee names with spaces and lower case
employees = ["  madhuri  ", "  ravi kumar ", "ANIL  ", "  priya"]

print("Original names:", employees)

# Task 1: Clean names - strip spaces and make Title case
clean_names = list(map(lambda name: name.strip().title(), employees))
print("\n1. Cleaned Names (strip + title):", clean_names)

# Task 2: Calculate total salary from basic salary
# basic = 30000, total = basic + bonus(10%) + hra(20%)
basic_salaries = [30000, 40000, 35000, 50000]

total_salaries = list(map(lambda sal: sal + sal*0.10 + sal*0.20, basic_salaries))
print("\n2. Basic Salaries:", basic_salaries)
print("   Total Salaries (basic+10%+20%):", total_salaries)

# Task 3: map() with 2 lists - Add bonus from two lists
basic = [30000, 40000, 50000]
bonus = [3000, 4000, 5000]

total = list(map(lambda b, bo: b + bo, basic, bonus))
print("\n3. Using map with 2 lists:")
print("   Basic:", basic)
print("   Bonus:", bonus)
print("   Total (basic+bonus):", total)

# Task 4: Convert string numbers to int
str_numbers = ["10", "20", "30", "40"]
int_numbers = list(map(int, str_numbers))
print("\n4. String to Int using map(int, list):")
print("   String numbers:", str_numbers)
print("   Int numbers:", int_numbers, "- Now we can do sum:", sum(int_numbers))

Original names: ['  madhuri  ', '  ravi kumar ', 'ANIL  ', '  priya']

1. Cleaned Names (strip + title): ['Madhuri', 'Ravi Kumar', 'Anil', 'Priya']

2. Basic Salaries: [30000, 40000, 35000, 50000]
   Total Salaries (basic+10%+20%): [39000.0, 52000.0, 45500.0, 65000.0]

3. Using map with 2 lists:
   Basic: [30000, 40000, 50000]
   Bonus: [3000, 4000, 5000]
   Total (basic+bonus): [33000, 44000, 55000]

4. String to Int using map(int, list):
   String numbers: ['10', '20', '30', '40']
   Int numbers: [10, 20, 30, 40] - Now we can do sum: 100


In [24]:
# CELL 3: Why map() is useful

numbers = [1, 2, 3, 4, 5]

# 3 ways to square numbers
print("Original:", numbers)

# Way 1: For loop
squares_loop = []
for n in numbers:
    squares_loop.append(n**2)
print("\n1. For loop:", squares_loop)

# Way 2: map()
squares_map = list(map(lambda n: n**2, numbers))
print("2. map():", squares_map)

# Way 3: List Comprehension
squares_comp = [n**2 for n in numbers]
print("3. List Comprehension:", squares_comp)

print("\nAll give same result, but map() is shortest for simple functions")
print("map() is faster than loop for large data")

Original: [1, 2, 3, 4, 5]

1. For loop: [1, 4, 9, 16, 25]
2. map(): [1, 4, 9, 16, 25]
3. List Comprehension: [1, 4, 9, 16, 25]

All give same result, but map() is shortest for simple functions
map() is faster than loop for large data


part of the code demonstrates the concept:
list(map(calc_bonus, salaries)) 
-> Core concept - applying function calc_bonus to every item in salaries.map(lambda name: name.strip().title(), employees) 
-> map with lambda, shows we can apply multiple string operations to each name in one line.map(lambda b, bo: b + bo, basic, bonus) 
-> map with 2 lists, proves map can take more than one iterable.map(int, str_numbers) 
-> map with built-in function int, no need for lambda.

When I write map(lambda sal: sal*0.10, salaries),
Python takes first salary 30000, passes to lambda, lambda returns 3000.0, stores it. 
Then takes second 40000 -> 4000.0, and so on. 
It does not run loop in my code, but internally it loops. It is lazy - it calculates only when we do list(). 
This makes it memory efficient and faster.
In my cleaning example, each messy name goes through strip().title() one by one automatically.

FILTER():

filter() is a built-in function that filters items from a list. 
--> It keeps only the items that satisfy a condition and removes the rest.
--> While map() transforms every item, filter() SELECTS only some items.

In [25]:
# CELL 1: Basic filter()
print("=== filter() Built-in Function ===\n")

salaries = [25000, 30000, 45000, 20000, 50000, 35000]
print("Original salaries:", salaries)

# Without filter() - using loop
high_sal_loop = []
for sal in salaries:
    if sal > 30000:
        high_sal_loop.append(sal)
print("High salaries (>30000) with loop:", high_sal_loop)

# With filter() - One line
def is_high(sal):
    return sal > 30000

high_sal_filter = list(filter(is_high, salaries))
print("High salaries with filter(): ", high_sal_filter)

# Shorter with lambda
high_sal_lambda = list(filter(lambda sal: sal > 30000, salaries))
print("High salaries with filter+lambda:", high_sal_lambda)

print("\nfilter() returns filter object:")
obj = filter(lambda x: x > 30000, salaries)
print("Direct filter object:", obj)
print("After list():", list(obj))

=== filter() Built-in Function ===

Original salaries: [25000, 30000, 45000, 20000, 50000, 35000]
High salaries (>30000) with loop: [45000, 50000, 35000]
High salaries with filter():  [45000, 50000, 35000]
High salaries with filter+lambda: [45000, 50000, 35000]

filter() returns filter object:
Direct filter object: <filter object at 0x000001E68810EFB0>
After list(): [45000, 50000, 35000]


In [26]:
# CELL 2: Unique Example - Employee Data Filtering

employees = [
    {"name": "Madhuri", "salary": 30000, "dept": "IT", "age": 21},
    {"name": "Ravi", "salary": 45000, "dept": "HR", "age": 28},
    {"name": "Anil", "salary": 20000, "dept": "IT", "age": 24},
    {"name": "Priya", "salary": 50000, "dept": "IT", "age": 30},
    {"name": "Kiran", "salary": 35000, "dept": "Finance", "age": 22}
]

print("All Employees:")
for e in employees:
    print(e)

# Task 1: Filter IT department employees
it_employees = list(filter(lambda emp: emp["dept"] == "IT", employees))
print("\n1. IT Department Only:")
for e in it_employees:
    print(f"  {e['name']} - {e['dept']}")

# Task 2: Filter high salary > 35000
high_salary = list(filter(lambda emp: emp["salary"] > 35000, employees))
print("\n2. Salary > 35000:")
for e in high_salary:
    print(f"  {e['name']} - {e['salary']}")

# Task 3: Filter age 25+ and IT dept - two conditions
senior_it = list(filter(lambda emp: emp["age"] >= 25 and emp["dept"] == "IT", employees))
print("\n3. IT Dept and Age >=25:")
for e in senior_it:
    print(f"  {e['name']} - Age {e['age']}, Dept {e['dept']}")

# Task 4: Filter names starting with 'P' or 'M'
names_pm = ["Madhuri", "Ravi", "Anil", "Priya", "Mohan", "Kiran"]
filtered_names = list(filter(lambda n: n.startswith('P') or n.startswith('M'), names_pm))
print("\n4. Names starting with P or M:")
print(f"   Original: {names_pm}")
print(f"   Filtered: {filtered_names}")

# Task 5: Filter even numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
evens = list(filter(lambda x: x % 2 == 0, numbers))
print("\n5. Even numbers only:")
print(f"   Original: {numbers}")
print(f"   Evens: {evens}")

All Employees:
{'name': 'Madhuri', 'salary': 30000, 'dept': 'IT', 'age': 21}
{'name': 'Ravi', 'salary': 45000, 'dept': 'HR', 'age': 28}
{'name': 'Anil', 'salary': 20000, 'dept': 'IT', 'age': 24}
{'name': 'Priya', 'salary': 50000, 'dept': 'IT', 'age': 30}
{'name': 'Kiran', 'salary': 35000, 'dept': 'Finance', 'age': 22}

1. IT Department Only:
  Madhuri - IT
  Anil - IT
  Priya - IT

2. Salary > 35000:
  Ravi - 45000
  Priya - 50000

3. IT Dept and Age >=25:
  Priya - Age 30, Dept IT

4. Names starting with P or M:
   Original: ['Madhuri', 'Ravi', 'Anil', 'Priya', 'Mohan', 'Kiran']
   Filtered: ['Madhuri', 'Priya', 'Mohan']

5. Even numbers only:
   Original: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
   Evens: [2, 4, 6, 8, 10]


Difference between MAP() & FILTER():

In [27]:
# CELL 3: Difference between map() and filter()

numbers = [10, 20, 30, 40, 50]
print("Original:", numbers)

# map() - Transforms EVERY item
# It changes value
mapped = list(map(lambda x: x > 25, numbers))
print("\nmap(lambda x: x > 25, numbers):")
print(mapped, "-> Returns True/False for EVERY item, length same (5)")

# filter() - Selects SOME items
# It filters, does not change value
filtered = list(filter(lambda x: x > 25, numbers))
print("\nfilter(lambda x: x > 25, numbers):")
print(filtered, "-> Returns only items where condition True, length less (3)")

print("\nRule: map = transform all, filter = select some")

Original: [10, 20, 30, 40, 50]

map(lambda x: x > 25, numbers):
[False, False, True, True, True] -> Returns True/False for EVERY item, length same (5)

filter(lambda x: x > 25, numbers):
[30, 40, 50] -> Returns only items where condition True, length less (3)

Rule: map = transform all, filter = select some


 part of the code demonstrates the concept:
 list(filter(is_high, salaries)) 
 -> Core concept - keeps only where function returns True.filter(lambda emp: emp["dept"] == "IT", employees) 
 -> Filtering dict list with condition on key, shows real-world use.filter(lambda emp: emp["age"] >= 25 and emp["dept"] == "IT", employees) 
 -> Multiple conditions with and, advanced filtering.filter(lambda x: x % 2 == 0, numbers) 
 -> Classic filter example - even numbers.map() vs filter() comparison 
 -> Shows map returns 5 True/False, filter returns 3 actual numbers.

 concept works in my implementation:
When I write filter(lambda sal: sal > 30000, salaries), Python takes first salary 25000, passes to lambda 25000 > 30000 -> False, so discards it. Takes second 30000 -> 30000 > 30000 -> False, discards. Takes 45000 -> True, keeps it. So at end only salaries that satisfy condition remain. In employee example, emp["dept"] == "IT" is checked for each employee dict, only IT employees pass through strainer. It is lazy like map - it filters only when we do list().

ZIP():

zip() is a built-in function that combines two or more lists together.

It takes iterables based on the list sizes, until the size reduces according to the suitable set of tuples formed internally.
Zip can also be used to unzip the combined lists.

very useful when you have related data in separate lists and want to loop them together.

In [28]:
# CELL 1: Basic zip()
print("=== zip() Built-in Function ===\n")

names = ["Madhuri", "Ravi", "Anil"]
salaries = [30000, 40000, 50000]

print("Names:", names)
print("Salaries:", salaries)

# Without zip() - manual index
print("\nWithout zip() - using index:")
for i in range(len(names)):
    print(f" {names[i]} earns {salaries[i]}")

# With zip() - direct
print("\nWith zip() - clean:")
for name, sal in zip(names, salaries):
    print(f" {name} earns {sal}")

# What zip() returns
print("\nWhat zip() returns:")
zipped = zip(names, salaries)
print("Direct zip object:", zipped)
print("After list():", list(zipped))

# zip() stops at shortest list
names2 = ["Madhuri", "Ravi"]
salaries2 = [30000, 40000, 50000, 60000]
print("\nIf lists have different length (2 vs 4):")
print("Names:", names2)
print("Salaries:", salaries2)
print("zip result:", list(zip(names2, salaries2)), "- Only 2 pairs, extra 2 salaries ignored")

=== zip() Built-in Function ===

Names: ['Madhuri', 'Ravi', 'Anil']
Salaries: [30000, 40000, 50000]

Without zip() - using index:
 Madhuri earns 30000
 Ravi earns 40000
 Anil earns 50000

With zip() - clean:
 Madhuri earns 30000
 Ravi earns 40000
 Anil earns 50000

What zip() returns:
Direct zip object: <zip object at 0x000001E6881F0E80>
After list(): [('Madhuri', 30000), ('Ravi', 40000), ('Anil', 50000)]

If lists have different length (2 vs 4):
Names: ['Madhuri', 'Ravi']
Salaries: [30000, 40000, 50000, 60000]
zip result: [('Madhuri', 30000), ('Ravi', 40000)] - Only 2 pairs, extra 2 salaries ignored


When I write zip(["Madhuri", "Ravi"], [30000][40000]),
Python internally does: take 1st from both -> ("Madhuri", 30000), 
take 2nd from both -> ("Ravi", 40000). It creates an iterator that gives one pair at a time. 
When I do list(zip(...)) it collects all pairs. When lists have different length, it stops at shortest - so no error, extra items ignored. 
Unzip zip(_combined) works because _ unpacks [("Madhuri", 30000), ("Ravi", 40000)] into separate arguments, and zip then groups all first elements together and second elements together.

ENUMERATE():

enumerate() is a built-in function that adds a counter (index) to each item in a list.

If we need to add index values to our big list, enumerate halps to add those indexes, The inex number starts with zero(0) for item1.

But, if we can set the index starting value manually for user friendly.

In [29]:
# Employee Report with S.No and Bonus:
employees = ["Madhuri", "Ravi", "Anil", "Priya"]
salaries = [30000, 45000, 35000, 50000]

print("S.No | Employee | Salary | Bonus(10%) | Total")
print("-" * 50)

# enumerate gives index, zip combines name and salary
for s_no, (name, salary) in enumerate(zip(employees, salaries), start=1):
    bonus = salary * 0.10
    total = salary + bonus
    print(f"{s_no}    | {name:<8} | {salary}  | {bonus:<8} | {total}")

S.No | Employee | Salary | Bonus(10%) | Total
--------------------------------------------------
1    | Madhuri  | 30000  | 3000.0   | 33000.0
2    | Ravi     | 45000  | 4500.0   | 49500.0
3    | Anil     | 35000  | 3500.0   | 38500.0
4    | Priya    | 50000  | 5000.0   | 55000.0


enumerate(zip(employees, salaries), start=1) is the core. zip() joins name and salary, enumerate() adds automatic S.No starting from 1

How it works:
  zip makes pairs like ("Madhuri", 30000). enumerate adds counter: (1, ("Madhuri", 30000)). In loop we unpack as s_no, (name, salary). No manual count or range(len()) needed.

SORTED():

sorted() is a built-in function that returns a new sorted list from any iterable without changing the original data.

Sorted() function is used in list(), string(), tuple(), dictionary().

Difference from list.sort(): list.sort() sorts the same list and returns None, while sorted() creates a new sorted copy and keeps original safe.

In [30]:
# Sorting Employees by Salary

employees = [
    {"name": "Madhuri", "salary": 35000},
    {"name": "Ravi", "salary": 50000},
    {"name": "Anil", "salary": 30000},
    {"name": "Priya", "salary": 45000}
]

print("Original List:")
for emp in employees:
    print(emp)

# Sort by salary (ascending) using key, original list not changed
sorted_by_salary = sorted(employees, key=lambda emp: emp["salary"])

print("\nSorted by Salary (Low to High):")
for emp in sorted_by_salary:
    print(emp)

# Sort by salary descending
sorted_desc = sorted(employees, key=lambda emp: emp["salary"], reverse=True)

print("\nSorted by Salary (High to Low):")
for emp in sorted_desc:
    print(emp)

Original List:
{'name': 'Madhuri', 'salary': 35000}
{'name': 'Ravi', 'salary': 50000}
{'name': 'Anil', 'salary': 30000}
{'name': 'Priya', 'salary': 45000}

Sorted by Salary (Low to High):
{'name': 'Anil', 'salary': 30000}
{'name': 'Madhuri', 'salary': 35000}
{'name': 'Priya', 'salary': 45000}
{'name': 'Ravi', 'salary': 50000}

Sorted by Salary (High to Low):
{'name': 'Ravi', 'salary': 50000}
{'name': 'Priya', 'salary': 45000}
{'name': 'Madhuri', 'salary': 35000}
{'name': 'Anil', 'salary': 30000}


It keeps original employee list safe and creates two new sorted lists - one low to high salary and one high to low.

Part demonstrates concept: sorted(employees, key=lambda emp: emp["salary"]) is the core. key tells Python to sort by salary field, reverse=True sorts descending, and original list remains unchanged.

How it works: sorted() takes each dictionary, applies key function emp["salary"] to get 35000, 50000 etc., compares those values and arranges dictionaries in that order in a new list.

ANY():

any() is a built-in function that checks if at least one item in an iterable is True.
It returns True if any one element is True, otherwise False. If iterable is empty, it returns False.

In [31]:
# Check if any employee is eligible for bonus

salaries = [28000, 32000, 25000, 30000, 29000]

print("Salaries:", salaries)
print("Bonus Criteria: Salary > 40000")

# any() checks if at least one salary > 40000
is_any_eligible = any(sal > 40000 for sal in salaries)

print("\nIs any employee eligible?", is_any_eligible)

# Real use case in if condition
if any(sal > 40000 for sal in salaries):
    print("Yes, at least one employee gets bonus")
else:
    print("No employee eligible for bonus")

# Another check - any salary less than 26000?
has_low_salary = any(sal < 26000 for sal in salaries)
print(f"\nAny low salary (<26000) present?: {has_low_salary}")

Salaries: [28000, 32000, 25000, 30000, 29000]
Bonus Criteria: Salary > 40000

Is any employee eligible? False
No employee eligible for bonus

Any low salary (<26000) present?: True


What program does: 
It checks the salary list to see if any employee meets bonus criteria. First check >40000 returns False because no one has that high salary.
Second check <26000 returns True because 25000 exists.

Which part demonstrates concept: any(sal > 40000 for sal in salaries) is the core. The generator gives True/False for each salary, any() returns True if even one True is found.

How it works: For first check, it evaluates 28000>40000=False, 32000>40000=False... all False, so final False. For second check, it finds 25000<26000=True and immediately returns True without checking rest.

ANY():

all() is a built-in function that checks if every item in an iterable is True.
It returns True only if all elements are True, otherwise False.
If iterable is empty, it returns True.

It works opposite to any().
any() needs at least one True, 
all() needs every item True. 
Internally it works like AND operation - it checks one by one and stops as soon as it finds first False. 
If no False found, it returns True.

In [32]:
# Check if all employees meet minimum salary criteria

salaries = [30000, 35000, 40000, 32000, 45000]

print("Salaries:", salaries)
print("Company Rule: All salaries must be >= 30000")

# all() checks if every salary >= 30000
is_all_valid = all(sal >= 30000 for sal in salaries)

print(f"\nAll salaries valid?: {is_all_valid}")

# Real use in payroll approval
if all(sal >= 30000 for sal in salaries):
    print("Payroll Approved - All employees meet minimum salary")
else:
    print("Payroll Rejected - Some employees below minimum")

# Second test with one invalid salary
salaries2 = [30000, 28000, 40000, 32000]
print(f"\nSecond List: {salaries2}")
print(f"All >= 30000?: {all(sal >= 30000 for sal in salaries2)}")

Salaries: [30000, 35000, 40000, 32000, 45000]
Company Rule: All salaries must be >= 30000

All salaries valid?: True
Payroll Approved - All employees meet minimum salary

Second List: [30000, 28000, 40000, 32000]
All >= 30000?: False


What program does:
It validates payroll by checking if every salary meets minimum criteria. 
First list has all >=30000 so returns True and payroll approved.
Second list has 28000 so returns False.

Which part demonstrates concept: all(sal >= 30000 for sal in salaries) is the core. It generates True/False for each salary and returns True only if all are True.

How it works: It checks 30000>=30000=True, continues, 35000>=30000=True, continues... if all True, final True. In second list, it finds 28000>=30000=False and immediately returns False without checking rest.

ISINSTANCE():

isinstance() is a built-in function that checks if an object is an instance of a particular data type or class.
It returns True if object belongs to that type, otherwise False.

In [33]:
# Validate and process mixed salary data.

raw_data = [30000, 45000, "35000", 40000.5, None, 32000, [30000]]
clean_salaries = []

print("Raw Data:", raw_data)
print("\nCleaning Process:")

for item in raw_data:
    # Check if item is int or float - valid salary
    if isinstance(item, (int, float)):
        clean_salaries.append(item)
        print(f" {item} -> {type(item).__name__} : Valid, Added")
    else:
        print(f" {item} -> {type(item).__name__} : Invalid, Skipped")

print(f"\nClean Salaries: {clean_salaries}")
print(f"Total Valid: {len(clean_salaries)}")
print(f"Total Payroll: {sum(clean_salaries)}")

Raw Data: [30000, 45000, '35000', 40000.5, None, 32000, [30000]]

Cleaning Process:
 30000 -> int : Valid, Added
 45000 -> int : Valid, Added
 35000 -> str : Invalid, Skipped
 40000.5 -> float : Valid, Added
 None -> NoneType : Invalid, Skipped
 32000 -> int : Valid, Added
 [30000] -> list : Invalid, Skipped

Clean Salaries: [30000, 45000, 40000.5, 32000]
Total Valid: 4
Total Payroll: 147000.5


What program does: 
It processes mixed raw data containing int, string, None, list. It filters only valid salary types (int, float) and calculates total payroll.

Which part demonstrates concept:
isinstance(item, (int, float)) is the core. It checks if item is instance of int or float in one line using tuple. If True, data is accepted.

How it works: 
Python checks object type. For 30000, isinstance(30000, (int, float)) is True because 30000 is int. For "35000", it is str, not in (int, float) so False. This way only correct types pass validation before calculation.

ID():

id() is a built-in function that returns the unique memory address of an object in Python.
Every object you create gets a unique ID (a number) which is its location in memory. No two objects alive at same time have same id.

In [34]:
# Understanding reference sharing with id()

# Immutable - int
salary1 = 30000
salary2 = 30000

print("Immutable - int:")
print(f" salary1 = {salary1}, id: {id(salary1)}")
print(f" salary2 = {salary2}, id: {id(salary2)}")
print(f" Same id? {id(salary1) == id(salary2)} -> Python reuses small ints")

# Mutable - list
employees1 = ["Madhuri", "Ravi"]
employees2 = employees1  # reference, not copy
employees3 = employees1.copy()  # actual copy

print("\nMutable - list:")
print(f" employees1 id: {id(employees1)}")
print(f" employees2 = employees1 -> id: {id(employees2)} (Same)")
print(f" employees3 = copy -> id: {id(employees3)} (Different)")

# Proof: modifying same id affects both
employees1.append("Anil")
print(f"\nAfter employees1.append('Anil'):")
print(f" employees1: {employees1}")
print(f" employees2: {employees2} (Changed because same id)")
print(f" employees3: {employees3} (Not changed because different id)")

Immutable - int:
 salary1 = 30000, id: 2089637711248
 salary2 = 30000, id: 2089631661104
 Same id? False -> Python reuses small ints

Mutable - list:
 employees1 id: 2089637808448
 employees2 = employees1 -> id: 2089637808448 (Same)
 employees3 = copy -> id: 2089637810688 (Different)

After employees1.append('Anil'):
 employees1: ['Madhuri', 'Ravi', 'Anil']
 employees2: ['Madhuri', 'Ravi', 'Anil'] (Changed because same id)
 employees3: ['Madhuri', 'Ravi'] (Not changed because different id)


What program does: 
Shows difference between reference and copy using id(). For int, same value gets same id. For list, employees2 = employees1 shares same id so change reflects in both, while .copy() creates different id so remains safe.

Which part demonstrates concept:
id(salary1) and id(employees1) is the core. Comparing ids proves if two variables point to same memory location.

How it works: Python creates object in memory with unique id. id() returns that address. When you assign employees2 = employees1, no new object created, only same address copied. So both ids equal. copy() creates new object with new address, so ids differ and modifications are independent.