TRY:

--> try block protects program from crashing.
--> Put risky code in try. If error comes, except will handle it.
--> If we put risky code inside try. If it fails, Python goes to except instead of stopping. Program continues safely.

In [1]:
# Only try-except

def process_product_price(product_name, price_text):
    try:
        # Risky conversion - user may type "free" instead of number
        price_value = float(price_text)
        final_price = price_value + (price_value * 0.18)  # Adding 18% GST
        print(f"{product_name} | Base: {price_value} | With GST: {final_price}")
        
    except:
        print(f"Error for {product_name}: Invalid price '{price_text}' - must be number")

# Real time inputs from portal
print("Case 1: Valid")
process_product_price("Laptop Stand", "1200")

print("\nCase 2: Invalid - user typed text")
process_product_price("Mouse Pad", "free")

print("\nCase 3: Valid")
process_product_price("Keyboard", "2500.50")

Case 1: Valid
Laptop Stand | Base: 1200.0 | With GST: 1416.0

Case 2: Invalid - user typed text
Error for Mouse Pad: Invalid price 'free' - must be number

Case 3: Valid
Keyboard | Base: 2500.5 | With GST: 2950.59


What program does: 
Takes product price as text from website, converts to float and adds GST.

Which part demonstrates concept: 
try: block has float(price_text) which is risky. except: handles if conversion fails.

How it works: 
When price is "1200" conversion succeeds. When price is "free" it raises ValueError, try stops, except runs and prints error message. App does not crash, next product still processed.

EXCEPT:

--> except is the handler for error caught by try.
--> Without except, try alone has no meaning.
--> You can have multiple except for different error types - ZeroDivisionError, ValueError, etc. Or one generic except for all errors.

In [2]:
# except concept:

def calculate_delivery_charge(order_id, distance_km):
    try:
        # Risky: distance_km may be 0 or text
        charge = 50 + (distance_km * 10)
        per_km_rate = charge / distance_km  # Risky if distance is 0
        print(f"Order {order_id}: Distance {distance_km}km | Delivery Charge Rs.{charge} | Rate Rs.{per_km_rate:.2f}/km")
        
    except ZeroDivisionError:
        print(f"Order {order_id}: Failed - Distance cannot be 0km")
        
    except TypeError:
        print(f"Order {order_id}: Failed - Distance must be number, got '{distance_km}'")
        
    except:
        print(f"Order {order_id}: Failed - Unexpected error in distance")

# Real cases from delivery app
print("Case 1: Valid distance")
calculate_delivery_charge("ORD-501", 5)

print("\nCase 2: Distance 0 - ZeroDivisionError")
calculate_delivery_charge("ORD-502", 0)

print("\nCase 3: Text input - TypeError")
calculate_delivery_charge("ORD-503", "five km")

print("\nCase 4: Valid again, program still running")
calculate_delivery_charge("ORD-504", 12)

Case 1: Valid distance
Order ORD-501: Distance 5km | Delivery Charge Rs.100 | Rate Rs.20.00/km

Case 2: Distance 0 - ZeroDivisionError
Order ORD-502: Failed - Distance cannot be 0km

Case 3: Text input - TypeError
Order ORD-503: Failed - Distance must be number, got 'five km'

Case 4: Valid again, program still running
Order ORD-504: Distance 12km | Delivery Charge Rs.170 | Rate Rs.14.17/km


What program does: 
Calculates delivery charge. Division by distance is risky.

Which part demonstrates concept: 
except ZeroDivisionError: and except TypeError: - these are except handlers. They catch specific errors from try block and give professional message.

How it works: 
Python runs try. If distance_km=0, division fails, Python jumps to except ZeroDivisionError. If distance_km="five km", multiplication fails, jumps to except TypeError. Program does not stop, Case 4 still runs after errors.

ELSE:

--> else in error handling runs ONLY when try has no error.
--> If try succeeds, else executes. 
--> If try fails, else is skipped and except runs.

In [1]:
# else concept in try-except-else:

def verify_employee_badge(badge_code, employee_name):
    try:
        # Risky: badge_code must be numeric
        badge_num = int(badge_code)
        if badge_num <= 0:
            raise ValueError("Badge must be positive")
            
    except ValueError as ve:
        print(f"Access Denied for {employee_name}: Invalid badge '{badge_code}' -> {ve}")
        
    except Exception as e:
        print(f"Access Denied for {employee_name}: {e}")
        
    else:
        # This runs ONLY if try had no error
        # Professional success logic
        print(f"Access Granted for {employee_name}: Badge {badge_num} verified")
        print(f"-> Logging entry, Opening gate for {employee_name}")
        return True

# Tests
print("Case 1: Valid badge - else will run")
verify_employee_badge("4056", "Suresh")

print("\nCase 2: Invalid badge text - else will NOT run")
verify_employee_badge("AB-4056", "Riya")

print("\nCase 3: Negative badge - else will NOT run")
verify_employee_badge("-10", "Amit")

print("\nCase 4: Valid badge - else will run again")
verify_employee_badge("102", "Neha")

Case 1: Valid badge - else will run
Access Granted for Suresh: Badge 4056 verified
-> Logging entry, Opening gate for Suresh

Case 2: Invalid badge text - else will NOT run
Access Denied for Riya: Invalid badge 'AB-4056' -> invalid literal for int() with base 10: 'AB-4056'

Case 3: Negative badge - else will NOT run
Access Denied for Amit: Invalid badge '-10' -> Badge must be positive

Case 4: Valid badge - else will run again
Access Granted for Neha: Badge 102 verified
-> Logging entry, Opening gate for Neha


True

What program does:
Verifies employee badge number. If badge valid, grants access and logs entry.

Which part demonstrates concept: 
else: block with access granted logic. It runs only in Case 1 and 4 where try succeds.

How it works: 
In Case 1, int("4056") succeeds, no exception, so Python skips except and runs else - gate opens. In Case 2 and 3, try fails, Python jumps to except, and else is completely skipped. This proves else = success-only path.

FINALLY:

--> finally always runs, no matter what.
--> If try succeeds, finally runs. 
--> If try fails, except runs, then finally still runs. 
--> Even if return or crash, finally runs.
--> It is used for cleanup - closing file, closing database, ejecting card, turning off machine.

In [2]:
# finally concept:

def check_server_connection(server_name, response_time_ms):
    connection_open = False
    try:
        print(f"Connecting to {server_name}...")
        connection_open = True
        
        # Risky operation
        if response_time_ms <= 0:
            raise ValueError("Invalid response time")
        if response_time_ms > 5000:
            raise TimeoutError("Server timeout")
            
        print(f"{server_name} responded in {response_time_ms}ms - Status OK")
        
    except ValueError as v_err:
        print(f"{server_name} Failed: {v_err}")
        
    except TimeoutError as t_err:
        print(f"{server_name} Failed: {t_err}")
        
    finally:
        # Always runs - cleanup
        if connection_open:
            print(f"{server_name}: Closing connection, Releasing resources")
            connection_open = False
        print(f"{server_name}: Log saved\n")

# Tests
print("Case 1: Success - finally still runs")
check_server_connection("Payment-Gateway", 120)

print("Case 2: Timeout Error - finally still runs")
check_server_connection("Payment-Gateway", 8000)

print("Case 3: Value Error - finally still runs")
check_server_connection("Payment-Gateway", -50)

print("Program continues - server check completed for all")

Case 1: Success - finally still runs
Connecting to Payment-Gateway...
Payment-Gateway responded in 120ms - Status OK
Payment-Gateway: Closing connection, Releasing resources
Payment-Gateway: Log saved

Case 2: Timeout Error - finally still runs
Connecting to Payment-Gateway...
Payment-Gateway Failed: Server timeout
Payment-Gateway: Closing connection, Releasing resources
Payment-Gateway: Log saved

Case 3: Value Error - finally still runs
Connecting to Payment-Gateway...
Payment-Gateway Failed: Invalid response time
Payment-Gateway: Closing connection, Releasing resources
Payment-Gateway: Log saved

Program continues - server check completed for all


What program does: 
Simulates server connection check with risky response time validation.

Which part demonstrates concept: 
finally: block with closing connection and log saving. It executed in all 3 cases - success, timeout, value error.

How it works: 
In Case 1 try succeeds, except skipped, finally runs. In Case 2 and 3 try fails, except runs, then finally still runs. Finally guarantees cleanup, even if program had error.

RAISE:

--> 'raise' is used to create the error manually.
--> Generally, python shows error when there is a technical error in code. But, raise decides when to stop the program and shows error.
--> Usually, raise uses manually when the business rule is broken.

In [3]:
# raise concept:

def issue_library_card(member_name, member_age, pending_books):
    try:
        # Business rules - we raise error manually if rule broken
        if member_age < 12:
            raise ValueError(f"Age {member_age} is below minimum 12 years")
        
        if pending_books > 3:
            raise PermissionError(f"Too many pending books: {pending_books}, Max allowed is 3")
        
        if not member_name.strip():
            raise TypeError("Member name cannot be empty")
            
        # If no raise, success
        print(f"Library Card Issued for {member_name}, Age {member_age}")
        return True
        
    except ValueError as ve:
        print(f"Card Failed for {member_name}: {ve}")
    except PermissionError as pe:
        print(f"Card Failed for {member_name}: {pe}")
    except TypeError as te:
        print(f"Card Failed for {member_name}: {te}")

# Tests
print("Case 1: Valid")
issue_library_card("Anjali", 20, 1)

print("\nCase 2: Raise ValueError - age rule broken")
issue_library_card("Rahul", 10, 0)

print("\nCase 3: Raise PermissionError - pending books rule broken")
issue_library_card("Sneha", 22, 5)

print("\nCase 4: Raise TypeError - name empty")
issue_library_card("   ", 18, 0)
            

Case 1: Valid
Library Card Issued for Anjali, Age 20

Case 2: Raise ValueError - age rule broken
Card Failed for Rahul: Age 10 is below minimum 12 years

Case 3: Raise PermissionError - pending books rule broken
Card Failed for Sneha: Too many pending books: 5, Max allowed is 3

Case 4: Raise TypeError - name empty
Card Failed for    : Member name cannot be empty


What program does: 
Issues library card only if business rules pass - age >=12, pending books <=3, name not empty.

Which part demonstrates concept: 
raise ValueError(...), raise PermissionError(...), raise TypeError(...) lines. We manually raise error when rule breaks.

How it works: 
Python does not know library rules. So we check condition ourselves. In Case 2, member_age < 12 is true, so we raise ValueError. Raising immediately jumps to except ValueError and stops card issue. Same for other cases. raise lets us create professional custom errors.

ASSERET:

--> assert uses by developer to catch the bug earlier
--> Used to find the error while testing the code internally.
--> The program stops running and displays error when the condition fails.


In [4]:
# assert concept:

def calculate_bonus(sales_amount, employee_code):
    print(f"Processing Bonus for {employee_code}, Sales: {sales_amount}")
    
    # Developer checks - assert
    # These must be true, else there is bug in data
    assert sales_amount >= 0, f"Sales cannot be negative, got {sales_amount}"
    assert isinstance(sales_amount, (int, float)), "Sales must be number"
    assert employee_code.startswith("EMP-"), f"Invalid Employee Code {employee_code}"
    
    # If all asserts pass, main logic
    bonus = sales_amount * 0.10
    print(f"-> {employee_code} Bonus Calculated: Rs.{bonus}\n")
    return bonus

# Tests
print("Case 1: Valid - asserts pass silently")
calculate_bonus(50000, "EMP-204")

print("Case 2: Invalid sales negative - assert will fail")
try:
    calculate_bonus(-1000, "EMP-205")
except AssertionError as ae:
    print(f"Assert Caught: {ae}\n")

print("Case 3: Invalid code - assert will fail")
try:
    calculate_bonus(30000, "204")
except AssertionError as ae:
    print(f"Assert Caught: {ae}\n")

print("Case 4: Valid again - program still continues")
calculate_bonus(80000, "EMP-206")    

Case 1: Valid - asserts pass silently
Processing Bonus for EMP-204, Sales: 50000
-> EMP-204 Bonus Calculated: Rs.5000.0

Case 2: Invalid sales negative - assert will fail
Processing Bonus for EMP-205, Sales: -1000
Assert Caught: Sales cannot be negative, got -1000

Case 3: Invalid code - assert will fail
Processing Bonus for 204, Sales: 30000
Assert Caught: Invalid Employee Code 204

Case 4: Valid again - program still continues
Processing Bonus for EMP-206, Sales: 80000
-> EMP-206 Bonus Calculated: Rs.8000.0



8000.0

what program does: 
Calculates 10% bonus. Before calculation, checks if sales valid and employee code correct.

Which part demonstrates concept: 
assert sales_amount >= 0, assert isinstance(...), assert employee_code.startswith("EMP-") - three assert checks. They pass silently in Case 1 and 

4.How it works: 
In Case 1, condition sales_amount >=0 true, assert does nothing, bonus calculated. In Case 2, condition false, assert raises AssertionError with message "Sales cannot be negative". In Case 3, code does not start with "EMP-", assert fails. Assert is for catching developer/data bugs early before main logic.

CUSTOM EXCEPTIONS:

--> Custom Exception means : we create our own error type.
--> Python has built-in errors like ValueError, TypeError. 
--> But sometimes business rule needs specific error name like InsufficientBalanceError. 
--> We create a new class that inherits from Exception.
--> This makes code more readable and professional - you know exactly what went wrong by error name.

In [4]:
# 1. Create custom error
class SalaryTooLowError(Exception):
    pass

# 2. Use it
def hire_candidate(candidate_name, expected_salary):
    try:
        if expected_salary < 15000:
            raise SalaryTooLowError(f"Offer {expected_salary} for {candidate_name} is below minimum 15000")
        print(f"{candidate_name} Hired at {expected_salary}")
    except SalaryTooLowError as e:
        print(f"Hiring Failed: {e}")

# Test
hire_candidate("Varun", 20000)  # success
hire_candidate("Harsha", 10000)  # custom error raised

Varun Hired at 20000
Hiring Failed: Offer 10000 for Harsha is below minimum 15000


SalaryTooLowError name tells exact business rule failed, better than generic ValueError.

BUILT - IN - EXCEPTIONS:

VALUE ERROR:

--> ValueError happens when type is correct but value is wrong.
--> It is not syntax mistake, it is invalid content.

In [5]:
# ValueError: 

def set_product_rating(buyer_name, rating_input):
    try:
        print(f"Processing rating for {buyer_name}...")
        
        # This can raise ValueError if rating_input is not convertible
        rating_value = int(rating_input)
        
        # This also raises ValueError if value out of range
        if rating_value < 1 or rating_value > 5:
            raise ValueError(f"Rating {rating_value} is invalid, must be 1 to 5")
        
        print(f"Success: {buyer_name} gave rating {rating_value} star")
        
    except ValueError as ve:
        print(f"Failed for {buyer_name}: ValueError -> {ve}\n")

# Tests
set_product_rating("Lakshmi", "5")      # valid value
set_product_rating("Rohit", "seven")    # type ok (str) but content invalid -> ValueError from int()
set_product_rating("Divya", "10")        # convertible but out of range -> ValueError from raise

Processing rating for Lakshmi...
Success: Lakshmi gave rating 5 star
Processing rating for Rohit...
Failed for Rohit: ValueError -> invalid literal for int() with base 10: 'seven'

Processing rating for Divya...
Failed for Divya: ValueError -> Rating 10 is invalid, must be 1 to 5



What program does:
Takes product rating from buyer and validates it must be 1-5.

Which part demonstrates concept:
int(rating_input) and raise ValueError(...) both show ValueError. First is auto ValueError by Python, second is manual ValueError for business rule.

How it works: 
Case 1 value "5" is valid, converted. Case 2 value "seven" - string type ok but cannot convert to int, Python raises ValueError automatically. Case 3 value 10 converted but invalid range, we raise ValueError manually. Both are ValueError - type correct, value wrong.

TYPE ERROR:

--> TypeError happens when operation is applied on wrong data type.
--> Python knows the value, but that type does not support that operation.
--ValueError = type correct, value wrong. TypeError = type itself wrong.

In [6]:
# TypeError: 

def generate_invoice(client_name, unit_price, quantity):
    try:
        print(f"Generating invoice for {client_name}...")
        
        # This line will raise TypeError if types are wrong
        # e.g., unit_price is str or quantity is str
        total_amount = unit_price * quantity
        final_bill = total_amount + 100  # 100 is delivery charge
        
        print(f"Invoice Success for {client_name}: Total = {final_bill}\n")
        
    except TypeError as te:
        print(f"Invoice Failed for {client_name}: TypeError -> {te}\n")

# Tests with different names
print("Case 1: Correct types")
generate_invoice("Harsha", 250, 4)          # int * int -> ok

print("Case 2: TypeError - str * str not supported like this")
generate_invoice("Nisha", "250", "4")       # str * str -> TypeError

print("Case 3: TypeError - int + str")
generate_invoice("Imran", 250, "4")         # int*str ok but then int+str? Actually total becomes str, but let's try len()
try:
    print("Checking extra: len() on integer")
    print(len(100))
except TypeError as te:
    print(f"TypeError Demo: {te}")

Case 1: Correct types
Generating invoice for Harsha...
Invoice Success for Harsha: Total = 1100

Case 2: TypeError - str * str not supported like this
Generating invoice for Nisha...
Invoice Failed for Nisha: TypeError -> can't multiply sequence by non-int of type 'str'

Case 3: TypeError - int + str
Generating invoice for Imran...
Invoice Failed for Imran: TypeError -> can only concatenate str (not "int") to str

Checking extra: len() on integer
TypeError Demo: object of type 'int' has no len()


What program does: 
Calculates invoice total = unit_price _ quantity + delivery charge.
    
Which part demonstrates concept: 
unit_price _ quantity and total_amount + 100 lines. When types wrong, TypeError raised. Also len(100) demo - len expects list/string but got int.
    
How it works: 
Case 1 both ints, operation valid. Case 2 both str, Python cannot multiply str _ str, raises TypeError. Case 3 unit_price int, quantity str "4" - Python does 250 _ "4" gives "444... string, then adding 100 int to str fails TypeError. So error is about wrong type used for operation.

INDEX ERROR:

--> IndexError happens when we try to access index that does not exist in list, tuple, or string.
--> Python indexing starts at 0. 
--> If list has 3 items, valid indexes are 0,1,2. 
--> If we try list, Python raises IndexError - "list index out of range".[5]

In [7]:
# IndexError:

def get_daily_task(team_member, task_list, day_number):
    try:
        print(f"Fetching task for {team_member} on Day {day_number}...")

        # task_list index starts at 0, but day_number given is 1,2,3...
        # If day_number is more than length, IndexError occurs
        assigned_task = task_list[day_number - 1]

        print(f"Success: {team_member} Task = {assigned_task}\n")

    except IndexError as ie:
        print(f"Failed for {team_member}: IndexError -> {ie} (Day {day_number} not in list)\n")

# Task list has only 3 tasks
weekly_tasks = ["Design Logo", "Build Website", "Client Meeting"]

get_daily_task("Suresh", weekly_tasks, 1) # valid - index 0
get_daily_task("Kavya", weekly_tasks, 3) # valid - index 2
get_daily_task("Manoj", weekly_tasks, 5) # invalid - index 4 does not exist -> IndexError

Fetching task for Suresh on Day 1...
Success: Suresh Task = Design Logo

Fetching task for Kavya on Day 3...
Success: Kavya Task = Client Meeting

Fetching task for Manoj on Day 5...
Failed for Manoj: IndexError -> list index out of range (Day 5 not in list)



What program does: 
Fetches task from list based on day number. List has 3 tasks, so only Day 1 to 3 valid.

Which part demonstrates concept: 
task_list[day_number - 1] line. When day_number is 5, index 4 accessed which does not exist, so IndexError raised.

How it works: 
Case 1 day 1 -> index 0 exists -> success. 
Case 2 day 3 -> index 2 exists -> success.
Case 3 day 5 -> index 4 out of range, Python raises IndexError: list index out of range caught by except block.

KEY ERROR:

--> KeyError happens when we try to access a key that does not exist in a dictionary.
--> Dictionary is key-value pairs.
--> If we do dict["name"] but "name" key was never added, Python raises KeyError.
--> Different from IndexError - IndexError is for list index number, whereas; KeyError is for dictionary key name.

In [8]:
# KeyError: 

def show_employee_department(staff_name, company_directory, search_key):
    try:
        print(f"Searching {search_key} for {staff_name}...")

        # If search_key does not exist in dict, KeyError raised
        department = company_directory[search_key]

        print(f"Success: {staff_name} works in {department}\n")

    except KeyError as ke:
        print(f"Failed for {staff_name}: KeyError -> {ke} key not found\n")

# Dictionary with only 3 keys
employee_record = {
    "emp_id": "E789",
    "name": "Priya",
    "dept": "Marketing"
}

show_employee_department("Priya", employee_record, "dept")      # valid key
show_employee_department("Priya", employee_record, "salary")    # invalid key -> KeyError
show_employee_department("Priya", employee_record, "location")  # invalid key -> KeyError

Searching dept for Priya...
Success: Priya works in Marketing

Searching salary for Priya...
Failed for Priya: KeyError -> 'salary' key not found

Searching location for Priya...
Failed for Priya: KeyError -> 'location' key not found



What program does: 
Searches information from employee dictionary using given key.

Which part demonstrates concept: 
company_directory[search_key] line. When search_key is "salary", dictionary has no such key, so KeyError occurs.

How it works: 
Case 1 key "dept" exists -> value returned. Case 2 key "salary" not in dict -> Python raises KeyError: 'salary' caught in except. Case 3 same for "location". KeyError only comes in dictionaries when key missing.

ATTRIBUTE ERROR:

AttributeError comes when object does not have the attribute/method you called.
Like calling .append() on integer.

In [9]:
# AttributeError:

def format_branch_name(branch):
    try:
        # branch expected to be string which has lower()
        clean_name = branch.lower()
        print(f"Branch formatted: {clean_name}")
    except AttributeError as e:
        print(f"AttributeError: {e} -> {branch} is {type(branch).__name__}, no lower()")

format_branch_name("HYD MAIN")  # string has lower() - ok
format_branch_name(101)         # int has no lower() - AttributeError

Branch formatted: hyd main
AttributeError: 'int' object has no attribute 'lower' -> 101 is int, no lower()


How my code works: branch.lower() is valid only for str. When 101 int passed, AttributeError raised.

NAME ERROR:

--> NameError happens when Python cannot find the name you used.
--> It means variable, function, or class not defined before use, or spelling mistake.

In [10]:
# NameError:

def print_order_details():
    customer = "Vijay"
    order_amount = 1500
    
    try:
        # discount_code is never defined - will raise NameError
        final_price = order_amount - discount_code
        print(final_price)
    except NameError as e:
        print(f"NameError: {e}")
        print(f"Fix: Variable 'discount_code' is not defined for {customer}")

print_order_details()

NameError: name 'discount_code' is not defined
Fix: Variable 'discount_code' is not defined for Vijay


What program does:
calculates final price with discount.

Which part code demonstrates:
discount_code variable never created before use.

How it works:
Python searches for name discount_code, not found in local or global scope, raises NameError.

FILE NOT FOUND ERROR:

--> FileNotFoundError happens when Python tries to open or read a file that does not exist on given path. 
--> It is sub-type of OSError.

In [11]:
# FileNotFoundError:

def load_report(staff_name, file_path):
    try:
        print(f"{staff_name} trying to open: {file_path}")
        with open(file_path, 'r') as f:
            data = f.read()
            print(data)
    except FileNotFoundError as e:
        print(f"FileNotFoundError: {e}")
        print(f"Fix: File does not exist for {staff_name}")

load_report("Anil", "monthly_sales.csv")  # file not present -> error

Anil trying to open: monthly_sales.csv
FileNotFoundError: [Errno 2] No such file or directory: 'monthly_sales.csv'
Fix: File does not exist for Anil


What program does:
tries to open file.

Which part code demonstrates:
open(file_path, 'r') when file missing.

How it works: 
OS searches path, not found, Python raises FileNotFoundError.

ZERO DIVISION ERROR:

--> ZeroDivisionError happens when we try to divide any number by zero. 
--> Maths rule - division by zero is undefined, 
--> so Python raises error to stop.

In [12]:
# Zero Division Error:

def calculate_avg_rating(artist_name, total_stars, total_reviews):
    try:
        print(f"Calculating avg for {artist_name}...")
        avg = total_stars / total_reviews
        print(f"Avg Rating: {avg}")
    except ZeroDivisionError as e:
        print(f"ZeroDivisionError: {e} -> total_reviews is 0 for {artist_name}")

calculate_avg_rating("Lalitha", 50, 10)  # valid
calculate_avg_rating("Kiran", 45, 0)     # division by zero -> error

Calculating avg for Lalitha...
Avg Rating: 5.0
Calculating avg for Kiran...
ZeroDivisionError: division by zero -> total_reviews is 0 for Kiran


What program does:
calculates average rating.

Which part code demonstrates:
total_stars / total_reviews when total_reviews=0.

How it works:
Python detects denominator 0, raises ZeroDivisionError, caught in except.

IMPORT ERROR:

--> ImportError happens when Python fails to import a module or name from module. 
--> It means module does not exist, not installed, or specific function/class not present in that module.

In [13]:
# ImportError:

def load_library_features(librarian_name):
    try:
        print(f"{librarian_name} loading special math function...")
        
        # math module exists, but 'cube' function does not exist in math
        from math import cube  

        print(cube(3))

    except ImportError as e:
        print(f"ImportError: {e}")
        print(f"Fix: 'cube' not found in math for {librarian_name}")

load_library_features("Sneha")

# Second case: module itself not exist
try:
    import fasttrack_analytics  # fake module
except ImportError as e:
    print(f"ImportError: {e} -> Module does not exist")

Sneha loading special math function...
ImportError: cannot import name 'cube' from 'math' (unknown location)
Fix: 'cube' not found in math for Sneha
ImportError: No module named 'fasttrack_analytics' -> Module does not exist


What program does:
tries to import non-existing name/module.

Which part code demonstrates:
from math import cube and import fasttrack_analytics.

How it works:
Python searches math for cube, not found, raises ImportError. Second case module itself not installed, also ImportError.

MODULE NOT FOUND ERROR:

--> ModuleNotFoundError is sub-type of ImportError. 
--> It happens only when entire module does not exist or not installed in environment. 
--> Python searched sys.path and could not find module file.

In [14]:
# ModuleNotFoundError:

def generate_invoice(owner_name):
    try:
        print(f"{owner_name} trying to import payment gateway...")
        
        import razorpay_pro_max  # this module does not exist
        
        print("Payment module loaded")
        
    except ModuleNotFoundError as e:
        print(f"ModuleNotFoundError: {e}")
        print(f"Fix: Install module using pip install razorpay_pro_max for {owner_name}")

generate_invoice("Meena")

# Valid import for comparison
try:
    import math
    print(f"\nmath module found: sqrt(16) = {math.sqrt(16)}")
except ModuleNotFoundError:
    print("math not found")

Meena trying to import payment gateway...
ModuleNotFoundError: No module named 'razorpay_pro_max'
Fix: Install module using pip install razorpay_pro_max for Meena

math module found: sqrt(16) = 4.0


What program does: 
tries to import a fake payment module.

Which part code demonstrates:
import razorpay_pro_max line.

How it works:
Python looks for file razorpay_pro_max.py in system path, not found, raises ModuleNotFoundError. Real module like math loads successfully.